# Generated by Django 5.2.3 on 2025-07-29 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_itinerary', '0002_affiliatetrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('platform', models.CharField(choices=[('hotel', 'Hotel'), ('car', 'Car'), ('flight', 'Flight')], max_length=10)),
                ('base_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
