# Generated by Django 5.2.3 on 2025-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localexpertform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending'),
        ),
        migrations.AlterField(
            model_name='serviceproviderform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending'),
        ),
    ]
