# Generated by Django 5.2.3 on 2025-08-28 16:17

import django.core.files.storage
from django.db import migrations, models
import authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_localexpertform_short_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localexpertform',
            name='gov_id',
            field=models.FileField(storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='localExpert/'),
        ),
        migrations.AlterField(
            model_name='localexpertform',
            name='travel_licence',
            field=models.FileField(storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='localExpert/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderform',
            name='business_gst_tax',
            field=models.FileField(storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='serviceProvider/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderform',
            name='business_license',
            field=models.FileField(storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='serviceProvider/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderform',
            name='business_logo',
            field=models.FileField(storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='serviceProvider/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderform',
            name='photo1',
            field=models.FileField(blank=True, null=True, storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='serviceProvider/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderform',
            name='photo2',
            field=models.FileField(blank=True, null=True, storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='serviceProvider/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderform',
            name='photo3',
            field=models.FileField(blank=True, null=True, storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='serviceProvider/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderform',
            name='photo4',
            field=models.FileField(blank=True, null=True, storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='serviceProvider/'),
        ),
        migrations.AlterField(
            model_name='serviceproviderform',
            name='photo5',
            field=models.FileField(blank=True, null=True, storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='serviceProvider/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='users/covers/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='users/images/'),
        ),
    ]
