# Generated by Django 5.2.3 on 2025-09-03 15:58

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False),
        )
    ]
