# Generated by Django 5.2.3 on 2025-12-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='toggle_role',
            field=models.CharField(choices=[('user', 'user'), ('local_expert', 'local_expert'), ('service_provider', 'service_provider')], default='User', max_length=20),
        ),
    ]
