# Generated by Django 5.2.3 on 2025-12-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_toggle_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_months',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='travel_style',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
