# Generated by Django 5.2.3 on 2025-08-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_itinerary', '0005_userandexpertchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplaceresults',
            name='image_url',
            field=models.JSONField(default=list),
        ),
    ]
