# Generated by Django 5.2.1 on 2025-07-28 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_itinerary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('place_data', models.JSONField(default=list)),
                ('hotel_data', models.JSONField(default=list)),
                ('service_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_trip', to='ai_itinerary.trip')),
            ],
        ),
    ]
