# Generated by Django 5.2.3 on 2025-08-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_itinerary', '0007_userandexpertchat_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userandexpertchat',
            name='attachment',
            field=models.FileField(null=True, upload_to='trip_expert_advice/'),
        ),
    ]
