# Generated by Django 5.2.3 on 2025-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_subscription_plan_remove_subscription_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousAPIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('api_name', models.CharField(max_length=100)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ip_address', 'api_name')},
            },
        ),
    ]
