# Generated by Django 5.2.3 on 2025-08-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_anonymousapiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECHARGE', 'Recharge'), ('API_USAGE', 'API Usage'), ('REFUND', 'Refund'), ('CREDIT_RECHARGE', 'Credit Recharge'), ('CREDIT_USAGE', 'Credit Usage')], max_length=20),
        ),
    ]
