# Generated by Django 5.2.3 on 2025-08-23 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_wallet_credits_wallettransaction_credits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAndExpertContract',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_title', models.CharField(max_length=300)),
                ('trip_to', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('attachment', models.FileField(null=True, upload_to='trip_expert_advice/')),
                ('contract_created_by', models.CharField(choices=[('user', 'User'), ('expert', 'Expert')], max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_expert_id_key', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_user_id_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractTransaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction_id', models.CharField(max_length=150)),
                ('transaction_type', models.CharField(choices=[('recharge', 'Recharge'), ('api_usage', 'API Usage'), ('refund', 'Refund'), ('credit_recharge', 'Credit Recharge'), ('credit_usage', 'Credit Usage'), ('contract_transaction', 'Contract Transaction')], max_length=50)),
                ('payment_status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('requires_capture', 'Requires Capture'), ('canceled', 'Canceled'), ('succeeded', 'Succeeded')], max_length=60)),
                ('is_succeeded', models.BooleanField()),
                ('paid_to_expert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_transaction_expert_id_key', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_transaction_user_id_key', to=settings.AUTH_USER_MODEL)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_transaction_contract_id_key', to='subscription.userandexpertcontract')),
            ],
        ),
    ]
