# Generated by Django 5.2.3 on 2025-12-16 16:36

import authentication.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, storage=authentication.models.UUIDTimeStampedFileSystemStorage(), upload_to='faq_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
