# Generated by Django 5.2.3 on 2025-09-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviderapp', '0003_alter_allservice_service_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='allservice',
            name='location',
            field=models.CharField(default='India', help_text='Service location (city, area, etc.)', max_length=255),
        ),
    ]
