# Generated by Django 5.2.1 on 2025-07-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_localexpertform_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localexpertform',
            name='languages',
            field=models.JSONField(default=list),
        ),
    ]
