# Generated by Django 5.2.1 on 2025-07-08 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_localexpertform_demo_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_service_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ServiceProviderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.TextField()),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField()),
                ('whatsapp', models.CharField()),
                ('country', models.CharField()),
                ('address', models.TextField()),
                ('booking_link', models.TextField(blank=True, null=True)),
                ('gst', models.CharField()),
                ('instagram_link', models.TextField(blank=True, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('linkedin_link', models.TextField(blank=True, null=True)),
                ('photo1', models.FileField(blank=True, null=True, upload_to='serviceProvider/')),
                ('photo2', models.FileField(blank=True, null=True, upload_to='serviceProvider/')),
                ('photo3', models.FileField(blank=True, null=True, upload_to='serviceProvider/')),
                ('photo4', models.FileField(blank=True, null=True, upload_to='serviceProvider/')),
                ('photo5', models.FileField(blank=True, null=True, upload_to='serviceProvider/')),
                ('business_type', models.CharField()),
                ('service_offers', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('instant_booking', models.BooleanField(default=False)),
                ('business_logo', models.FileField(upload_to='serviceProvider/')),
                ('business_license', models.FileField(upload_to='serviceProvider/')),
                ('business_gst_tax', models.FileField(upload_to='serviceProvider/')),
                ('t_and_c', models.BooleanField(default=False)),
                ('info_confirmation', models.BooleanField(default=False)),
                ('contact_request', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
