// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/billboard/Curated.tsx": () => import("../components/mockups/billboard/Curated.tsx"),
  "./components/mockups/billboard/Current.tsx": () => import("../components/mockups/billboard/Current.tsx")
};
