#!/usr/bin/env tsx

/**
 * Popular Cities Content Seed
 *
 * Seeds hidden gems (8 per city) and at least one active providerServices
 * row for Tokyo, Kyoto, and Paris so the location feed is never empty in a
 * fresh environment.
 *
 * Each city has gems covering all four feed categories:
 *   Eat  — placeType includes: restaurant | cafe | dining | food
 *   Do   — placeType includes: attraction | activity | temple | shrine | park
 *   Stay — placeType includes: hotel | ryokan | hostel
 *   Photo— placeType includes: viewpoint | scenic | photo spot | photography
 *
 * Neighborhood slugs match those in city-neighborhoods.seed.ts.
 *
 * Idempotent: skips rows whose (city, placeName) already exist.
 * Provider services: creates a deterministic seed provider user if none exist.
 *
 * Run standalone: `tsx server/seeds/popular-cities-content.seed.ts`
 */

import { db } from "../db";
import { travelPulseHiddenGems, providerServices, users } from "@shared/schema";
import { and, eq, ilike, isNull, or } from "drizzle-orm";
import { logger } from "../infrastructure";
import { resolveNeighborhoodCentroid } from "./lib/neighborhood-centroid";

interface GemSeed {
  city: string;
  country: string;
  placeName: string;
  placeType: string;
  address?: string;
  latitude: string;
  longitude: string;
  localRating: string;
  touristMentions: number;
  localMentions: number;
  gemScore: number;
  discoveryStatus: string;
  daysUntilMainstream?: number;
  description: string;
  whyLocalsLoveIt: string;
  bestFor: string[];
  priceRange: string;
  neighborhood: string;
  imageUrl?: string;
}

const HIDDEN_GEMS: GemSeed[] = [
  // ── TOKYO (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ─────────────────────
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Kayaba Coffee",
    placeType: "cafe",
    address: "6-1-29 Yanaka, Taito City, Tokyo",
    latitude: "35.7234000",
    longitude: "139.7657000",
    localRating: "4.7",
    touristMentions: 120,
    localMentions: 890,
    gemScore: 82,
    discoveryStatus: "hidden",
    daysUntilMainstream: 180,
    description: "A beautifully preserved 1930s wooden coffee house in the Yanaka shitamachi. Famous for its thick tamago-sando egg sandwich and single-origin pour-over.",
    whyLocalsLoveIt: "Time-stands-still atmosphere, no Instagram crowds, and the best morning set in east Tokyo.",
    bestFor: ["slow mornings", "breakfast", "solo travel"],
    priceRange: "$",
    neighborhood: "yanaka",
    imageUrl: "https://images.unsplash.com/photo-1576618148400-f54bbd73ed4f?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Nakameguro Koukashita",
    placeType: "restaurant",
    address: "Under the Tokyu Toyoko Line, Meguro City, Tokyo",
    latitude: "35.6442000",
    longitude: "139.6979000",
    localRating: "4.6",
    touristMentions: 200,
    localMentions: 1500,
    gemScore: 74,
    discoveryStatus: "emerging",
    daysUntilMainstream: 90,
    description: "A curated strip of micro-restaurants, craft-beer bars, and coffee roasters built under the elevated rail line along the Meguro canal.",
    whyLocalsLoveIt: "Canal views, zero tourist traps, and genuinely creative chefs working tiny open kitchens.",
    bestFor: ["date night", "craft beer", "evening out"],
    priceRange: "$$",
    neighborhood: "nakameguro",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Asakusa Hoppy Street Yakitori",
    placeType: "dining",
    address: "Hoppy-dori, Asakusa, Taito City, Tokyo",
    latitude: "35.7146000",
    longitude: "139.7945000",
    localRating: "4.5",
    touristMentions: 300,
    localMentions: 1800,
    gemScore: 71,
    discoveryStatus: "emerging",
    daysUntilMainstream: 60,
    description: "A rowdy pedestrian street where Tokyo working-class culture has thrived since the post-war era. Plastic stools, cheap hoppy beer, and shichirin grilled skewers.",
    whyLocalsLoveIt: "Unpretentious, dirt cheap, and utterly authentic. The grilled chicken skewers here have been perfected over decades.",
    bestFor: ["budget dining", "local culture", "street food"],
    priceRange: "$",
    neighborhood: "asakusa",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Golden Gai Late-Night Bars",
    placeType: "attraction",
    address: "Golden Gai, Kabukicho, Shinjuku City, Tokyo",
    latitude: "35.6940000",
    longitude: "139.7050000",
    localRating: "4.9",
    touristMentions: 500,
    localMentions: 3000,
    gemScore: 88,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "200+ micro-bars packed into six tiny alleyways. Each fits 6-8 people, has its own theme, and is run by a single bartender who often doubles as DJ.",
    whyLocalsLoveIt: "Nowhere else on earth feels like this after midnight. Each bar is a world unto itself.",
    bestFor: ["nightlife", "solo travel", "unique experience"],
    priceRange: "$$",
    neighborhood: "shinjuku",
    imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Disk Union Shimokitazawa",
    placeType: "activity",
    address: "2-25-8 Kitazawa, Setagaya City, Tokyo",
    latitude: "35.6617000",
    longitude: "139.6683000",
    localRating: "4.8",
    touristMentions: 85,
    localMentions: 1200,
    gemScore: 79,
    discoveryStatus: "hidden",
    daysUntilMainstream: 220,
    description: "Seven-floor vinyl heaven stacked with Japanese pressings, jazz, city pop, and rare imports. Each floor is a different genre — come prepared to stay for hours.",
    whyLocalsLoveIt: "Serious collectors come weekly. Late-70s Japanese city pop LPs go for a few hundred yen.",
    bestFor: ["music lovers", "rainy days", "unique souvenirs"],
    priceRange: "$",
    neighborhood: "shimokitazawa",
    imageUrl: "https://images.unsplash.com/photo-1494232410401-ad00d5433cfa?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Claska Hotel Meguro",
    placeType: "hotel",
    address: "1-3-18 Chuo-cho, Meguro City, Tokyo",
    latitude: "35.6425000",
    longitude: "139.7004000",
    localRating: "4.6",
    touristMentions: 180,
    localMentions: 600,
    gemScore: 72,
    discoveryStatus: "emerging",
    description: "A design-forward boutique hotel in a converted 1960s ryokan building. The Gallery shop on the ground floor is one of Tokyo's best curated design shops.",
    whyLocalsLoveIt: "The interiors are textbook Japanese minimal design. Locals come for the gallery even if they aren't staying.",
    bestFor: ["design lovers", "couples", "boutique stay"],
    priceRange: "$$$",
    neighborhood: "nakameguro",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Yanaka Cemetery Cherry Blossom Walk",
    placeType: "scenic",
    address: "7-5-24 Yanaka, Taito City, Tokyo",
    latitude: "35.7255000",
    longitude: "139.7633000",
    localRating: "4.8",
    touristMentions: 180,
    localMentions: 2200,
    gemScore: 81,
    discoveryStatus: "hidden",
    daysUntilMainstream: 250,
    description: "Yanaka Cemetery's main avenue becomes a canopy of sakura blossoms in late March — entirely free, almost entirely locals, and no crowds compared to Ueno or Shinjuku.",
    whyLocalsLoveIt: "The combination of ancient gravestones and sakura blossoms is uniquely Tokyo. Golden hour here is transcendent.",
    bestFor: ["photography", "cherry blossom season", "walking"],
    priceRange: "$",
    neighborhood: "yanaka",
    imageUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Nakameguro Canal Viewpoint at Dusk",
    placeType: "viewpoint",
    address: "Nakameguro, Meguro City, Tokyo",
    latitude: "35.6450000",
    longitude: "139.6990000",
    localRating: "4.9",
    touristMentions: 600,
    localMentions: 3500,
    gemScore: 84,
    discoveryStatus: "emerging",
    description: "The 2km canal walk glows copper at sunset as boutique café lights reflect off the water. The tree canopy forms tunnels best photographed 30 minutes before dark.",
    whyLocalsLoveIt: "One of Tokyo's best free photo spots at any season — the lantern glow in autumn is particularly stunning.",
    bestFor: ["photography", "evening walk", "golden hour"],
    priceRange: "$",
    neighborhood: "nakameguro",
    imageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=80",
  },

  // ── KYOTO (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ─────────────────────
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Ippodo Tea Kaboku Tearoom",
    placeType: "cafe",
    address: "52 Teramachi Nijo-agaru, Nakagyo Ward, Kyoto",
    latitude: "35.0156000",
    longitude: "135.7672000",
    localRating: "4.9",
    touristMentions: 150,
    localMentions: 2100,
    gemScore: 85,
    discoveryStatus: "hidden",
    daysUntilMainstream: 240,
    description: "Established in 1717, this is the definitive matcha source for Kyoto's tea masters. The adjoining Kaboku tearoom serves any tea from their range, brewed with precision.",
    whyLocalsLoveIt: "Serious tea culture, zero tourist kitsch. Staff guide you to the perfect sencha for your taste and budget.",
    bestFor: ["tea lovers", "cultural immersion", "quiet afternoon"],
    priceRange: "$$",
    neighborhood: "kawaramachi-sanjo",
    imageUrl: "https://images.unsplash.com/photo-1569144157591-c60f3f82f137?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Nishiki Market Side Alleys",
    placeType: "food",
    address: "Nishiki Market, Nakagyo Ward, Kyoto",
    latitude: "35.0052000",
    longitude: "135.7648000",
    localRating: "4.7",
    touristMentions: 800,
    localMentions: 3500,
    gemScore: 78,
    discoveryStatus: "emerging",
    description: "Kyoto's 'kitchen' market — 100+ stalls of pickled vegetables, fresh tofu, grilled skewers, and seasonal sweets. The perpendicular side alleys have the best value eating.",
    whyLocalsLoveIt: "Grandmothers still shop here for their daily pickles. The tsukemono variety is unmatched anywhere.",
    bestFor: ["food tasting", "local culture", "lunch"],
    priceRange: "$",
    neighborhood: "kawaramachi-sanjo",
    imageUrl: "https://images.unsplash.com/photo-1564419320461-6870880221ad?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Kanga-an Temple Shojin Ryori",
    placeType: "restaurant",
    address: "17 Miyanishicho, Kita Ward, Kyoto",
    latitude: "35.0454000",
    longitude: "135.7447000",
    localRating: "4.8",
    touristMentions: 60,
    localMentions: 480,
    gemScore: 86,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A 17th-century Zen temple offering shojin ryori Buddhist vegetarian cuisine in private tatami rooms overlooking a moss garden. Reservation weeks in advance required.",
    whyLocalsLoveIt: "The seasonally changing menu is sourced entirely from the temple's own garden. An experience impossible to replicate.",
    bestFor: ["fine dining", "vegetarian", "cultural immersion"],
    priceRange: "$$$",
    neighborhood: "nishijin",
    imageUrl: "https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Fushimi Inari Pre-Dawn Hike",
    placeType: "attraction",
    address: "68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto",
    latitude: "34.9671000",
    longitude: "135.7727000",
    localRating: "5.0",
    touristMentions: 2000,
    localMentions: 4000,
    gemScore: 92,
    discoveryStatus: "hidden",
    daysUntilMainstream: 730,
    description: "The 10,000 torii path is magical but overcrowded by 8am. Arriving at 4:30am means walking the full summit trail completely alone in mist and candlelight.",
    whyLocalsLoveIt: "Dawn at the summit is a genuinely spiritual experience. Most tourists only do the first 30 minutes.",
    bestFor: ["hiking", "spiritual experience", "avoiding crowds"],
    priceRange: "$",
    neighborhood: "fushimi",
    imageUrl: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Pontocho Alley Evening Stroll",
    placeType: "activity",
    address: "Pontocho, Nakagyo Ward, Kyoto",
    latitude: "35.0083000",
    longitude: "135.7707000",
    localRating: "4.8",
    touristMentions: 900,
    localMentions: 2800,
    gemScore: 80,
    discoveryStatus: "emerging",
    description: "A 500-metre stone alley running parallel to the Kamo River. In summer, restaurants extend kawayuka elevated platforms over the water for open-air dining.",
    whyLocalsLoveIt: "The pre-dinner golden hour with lanterns just lit and no crowds is the most photogenic moment in all Kyoto.",
    bestFor: ["evening walk", "summer dining", "atmosphere"],
    priceRange: "$$",
    neighborhood: "pontocho",
    imageUrl: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Yoshida Sanso Ryokan",
    placeType: "ryokan",
    address: "59-1 Yoshida Shimoadachi-cho, Sakyo Ward, Kyoto",
    latitude: "35.0267000",
    longitude: "135.7839000",
    localRating: "4.9",
    touristMentions: 95,
    localMentions: 520,
    gemScore: 88,
    discoveryStatus: "hidden",
    daysUntilMainstream: 400,
    description: "A converted 1932 Imperial guesthouse on the forested slopes of Mount Yoshida. Nine suites, a private garden, and multi-course kaiseki dinner served in your room.",
    whyLocalsLoveIt: "The Japanese imperial hospitality tradition is alive here. No-one rushes you, no-one under 18, pure Kyoto.",
    bestFor: ["luxury stay", "couples", "authentic ryokan"],
    priceRange: "$$$$",
    neighborhood: "higashiyama",
    imageUrl: "https://images.unsplash.com/photo-1548165892-cd6be85a7f69?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Fushimi Inari Torii Tunnel at Dawn",
    placeType: "viewpoint",
    address: "Fushimi Inari Taisha, Fushimi Ward, Kyoto",
    latitude: "34.9673000",
    longitude: "135.7729000",
    localRating: "5.0",
    touristMentions: 1500,
    localMentions: 3800,
    gemScore: 93,
    discoveryStatus: "hidden",
    daysUntilMainstream: 730,
    description: "The lower torii tunnel photographed empty at 5am, backlit by the first sun slicing through the orange gates. Arguably the best photo opportunity in all of Japan.",
    whyLocalsLoveIt: "By 9am this exact spot has 200 people queuing. At dawn it is yours alone and lit like a film set.",
    bestFor: ["photography", "dawn", "iconic shot"],
    priceRange: "$",
    neighborhood: "fushimi",
    imageUrl: "https://images.unsplash.com/photo-1580917922805-21d32edd27e3?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Philosopher's Path Canal in Autumn",
    placeType: "scenic",
    address: "Tetsugaku no Michi, Sakyo Ward, Kyoto",
    latitude: "35.0168000",
    longitude: "135.7940000",
    localRating: "4.7",
    touristMentions: 600,
    localMentions: 2000,
    gemScore: 75,
    discoveryStatus: "emerging",
    description: "The canal-side path connecting Nanzen-ji to Ginkaku-ji. Less visited in autumn than spring, the red maple canopy over the water is arguably more beautiful than sakura season.",
    whyLocalsLoveIt: "Autumn maples reflected in the still canal at 7am — one of Kyoto's secret great photos.",
    bestFor: ["photography", "autumn foliage", "walking", "golden hour"],
    priceRange: "$",
    neighborhood: "higashiyama",
    imageUrl: "https://images.unsplash.com/photo-1601823984263-6ec76b4c8aaf?auto=format&fit=crop&w=800&q=80",
  },

  // ── PARIS (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ─────────────────────
  {
    city: "Paris",
    country: "France",
    placeName: "Au Passage Natural Wine Bar",
    placeType: "restaurant",
    address: "1bis Passage Saint-Sebastien, 75011 Paris",
    latitude: "48.8605000",
    longitude: "2.3715000",
    localRating: "4.8",
    touristMentions: 120,
    localMentions: 1800,
    gemScore: 83,
    discoveryStatus: "hidden",
    daysUntilMainstream: 180,
    description: "A cult natural-wine bar and small plates restaurant hidden in a covered passage near Republique. The lamb neck croquettes and the wine list are the talk of Paris's chef community.",
    whyLocalsLoveIt: "Zero decor investment, maximum food and wine obsession. The chefs here go on to run Paris's hottest tables.",
    bestFor: ["natural wine", "small plates", "date night", "foodie"],
    priceRange: "$$",
    neighborhood: "bastille",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Marche d'Aligre Sunday Morning",
    placeType: "food",
    address: "Place d'Aligre, 75012 Paris",
    latitude: "48.8500000",
    longitude: "2.3740000",
    localRating: "4.8",
    touristMentions: 180,
    localMentions: 3200,
    gemScore: 84,
    discoveryStatus: "hidden",
    daysUntilMainstream: 200,
    description: "The most Parisian market in Paris — outdoor flea stalls from 7am Thursday to Sunday, surrounded by covered food halls with oysters, charcuterie, and cheese.",
    whyLocalsLoveIt: "Flea items for 2 euros that cost 50 in Le Marais. The Beauvau covered hall has the best oyster bar in the 12th.",
    bestFor: ["bargain hunting", "food tasting", "local culture", "morning"],
    priceRange: "$",
    neighborhood: "bastille",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Cafe de la Mairie Saint-Sulpice",
    placeType: "cafe",
    address: "8 Place Saint-Sulpice, 75006 Paris",
    latitude: "48.8506000",
    longitude: "2.3333000",
    localRating: "4.6",
    touristMentions: 90,
    localMentions: 1500,
    gemScore: 78,
    discoveryStatus: "hidden",
    daysUntilMainstream: 210,
    description: "An unchanged 1950s zinc-bar cafe facing the Saint-Sulpice fountain — Sontag, Perec, and Fitzgerald all drank here. Terrace seats at normal French cafe prices.",
    whyLocalsLoveIt: "The best people-watching terrace on the Left Bank. No gimmicks, perfect crepes, honest pricing.",
    bestFor: ["coffee", "writing", "people watching", "literary Paris"],
    priceRange: "$",
    neighborhood: "saint-germain",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Buttes-Chaumont Park",
    placeType: "park",
    address: "Parc des Buttes-Chaumont, 75019 Paris",
    latitude: "48.8788000",
    longitude: "2.3817000",
    localRating: "4.9",
    touristMentions: 250,
    localMentions: 4500,
    gemScore: 87,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "Paris's most dramatic park — a Victorian landscape with a rocky island temple, suspension bridge, and sweeping panoramas. Locals picnic here while tourists queue at the Eiffel Tower.",
    whyLocalsLoveIt: "The island temple view at golden hour is equal to any postcard Paris. Completely free and uncrowded.",
    bestFor: ["picnic", "families", "afternoon escape", "views"],
    priceRange: "$",
    neighborhood: "belleville",
    imageUrl: "https://images.unsplash.com/photo-1551918120-9739cb430c6d?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Coulee Verte Elevated Park",
    placeType: "attraction",
    address: "Promenade Plantee, 75012 Paris",
    latitude: "48.8485000",
    longitude: "2.3762000",
    localRating: "4.7",
    touristMentions: 200,
    localMentions: 2800,
    gemScore: 80,
    discoveryStatus: "hidden",
    daysUntilMainstream: 270,
    description: "The world's first elevated park, built on a 19th-century railway viaduct above the 12th arrondissement — predating New York's High Line by 15 years. Gardens and city views from 10m up.",
    whyLocalsLoveIt: "A green ribbon of calm above street noise. The viaduct arches below are now art galleries worth exploring too.",
    bestFor: ["walking", "urban exploration", "gardens"],
    priceRange: "$",
    neighborhood: "bastille",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Hotel du Petit Moulin Le Marais",
    placeType: "hotel",
    address: "29-31 Rue de Poitou, 75003 Paris",
    latitude: "48.8612000",
    longitude: "2.3597000",
    localRating: "4.7",
    touristMentions: 160,
    localMentions: 480,
    gemScore: 77,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A 17th-century bakery — the oldest in Paris — converted into a 17-room design hotel by Christian Lacroix. Every room has a different hand-painted design.",
    whyLocalsLoveIt: "The building's history and Lacroix's artistry combine in ways no chain hotel ever could. No two rooms are the same.",
    bestFor: ["design lovers", "couples", "boutique stay", "Le Marais"],
    priceRange: "$$$",
    neighborhood: "le-marais",
    imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe2f5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Buttes-Chaumont Temple de la Sibylle Viewpoint",
    placeType: "viewpoint",
    address: "Ile du Belveder, Parc des Buttes-Chaumont, 75019 Paris",
    latitude: "48.8800000",
    longitude: "2.3820000",
    localRating: "4.9",
    touristMentions: 180,
    localMentions: 3000,
    gemScore: 88,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "Standing on the island summit temple gives a 360-degree panorama across Paris's rooftops and the Sacre-Coeur on the horizon — a view locals protect fiercely from overexposure.",
    whyLocalsLoveIt: "Better Parisian skyline view than the Eiffel Tower, completely free, and 90% fewer tourists.",
    bestFor: ["photography", "panoramic views", "golden hour"],
    priceRange: "$",
    neighborhood: "belleville",
    imageUrl: "https://images.unsplash.com/photo-1431274172761-fca41d930114?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Montmartre Vineyard Clos Montmartre",
    placeType: "scenic",
    address: "Rue des Saules, 75018 Paris",
    latitude: "48.8876000",
    longitude: "2.3405000",
    localRating: "4.7",
    touristMentions: 300,
    localMentions: 1200,
    gemScore: 75,
    discoveryStatus: "emerging",
    description: "Paris's last working vineyard in the 18th arrondissement — 1,700 bottles of Pinot Noir per year. The October harvest festival is a neighbourhood institution.",
    whyLocalsLoveIt: "Standing in a vineyard looking over Paris rooftops is surreal and secret. The October fete is the best local party of the year.",
    bestFor: ["photography", "wine lovers", "autumn visit", "unique experience"],
    priceRange: "$",
    neighborhood: "montmartre",
    imageUrl: "https://images.unsplash.com/photo-1471919743851-c3efa5059c11?auto=format&fit=crop&w=800&q=80",
  },

  // ── BARCELONA (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ──────────────────
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Bar Calders El Born Vermouth",
    placeType: "cafe",
    address: "Carrer del Parlament 25, 08015 Barcelona",
    latitude: "41.3779000",
    longitude: "2.1631000",
    localRating: "4.7",
    touristMentions: 90,
    localMentions: 1400,
    gemScore: 79,
    discoveryStatus: "hidden",
    daysUntilMainstream: 200,
    description: "A corner bar in Sant Antoni where Barcelona's creative class gathers on Sunday mornings for vermut, boquerones, and olives. The terrace spills onto the pavement and the kitchen closes when it feels like it.",
    whyLocalsLoveIt: "The Sunday vermouth ritual here is as authentic as it gets — no tourist menus, just house vermut and the newspaper.",
    bestFor: ["brunch", "vermouth", "local culture", "weekend morning"],
    priceRange: "$",
    neighborhood: "el-raval",
    imageUrl: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "El Xampanyet Cava Bar",
    placeType: "restaurant",
    address: "Carrer de Montcada 22, 08003 Barcelona",
    latitude: "41.3844000",
    longitude: "2.1818000",
    localRating: "4.8",
    touristMentions: 180,
    localMentions: 2200,
    gemScore: 82,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A Catalan cava bar opened in 1929, still run by the same family, just metres from the Picasso Museum. House cava is poured from unlabelled bottles and house-made anchovies are the must-order.",
    whyLocalsLoveIt: "This is the real El Born, unchanged and unhurried. Go before the Picasso Museum crowd spills in at noon.",
    bestFor: ["cava tasting", "pintxos", "historic venue", "couple"],
    priceRange: "$",
    neighborhood: "el-born",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Mercat de l'Abaceria Gràcia",
    placeType: "food",
    address: "Travessera de Gràcia 186, 08012 Barcelona",
    latitude: "41.4058000",
    longitude: "2.1563000",
    localRating: "4.6",
    touristMentions: 60,
    localMentions: 1100,
    gemScore: 76,
    discoveryStatus: "hidden",
    daysUntilMainstream: 250,
    description: "A 19th-century iron market in Gràcia that locals fiercely protect from the La Boqueria crowds. Organic produce, local cheeses, wild mushrooms, and an honest neighbourhood bar inside.",
    whyLocalsLoveIt: "The best market in Barcelona for actual shopping. Stallholders know your name here — no performance for tourists.",
    bestFor: ["food shopping", "local culture", "morning", "picnic supplies"],
    priceRange: "$",
    neighborhood: "gracia",
    imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Bunkers del Carmel Sunset Viewpoint",
    placeType: "viewpoint",
    address: "Turó de la Rovira, 08032 Barcelona",
    latitude: "41.4180000",
    longitude: "2.1545000",
    localRating: "4.9",
    touristMentions: 400,
    localMentions: 3800,
    gemScore: 90,
    discoveryStatus: "hidden",
    daysUntilMainstream: 400,
    description: "The ruins of a Civil War anti-aircraft battery on Barcelona's highest accessible hill. A 360-degree city panorama — Sagrada Família, Tibidabo, the sea — that no paid viewpoint in the city rivals.",
    whyLocalsLoveIt: "Locals bring wine, blankets and guitars at sunset. The view is better than the Sagrada Família rooftop and completely free.",
    bestFor: ["photography", "sunset", "panoramic views", "picnic"],
    priceRange: "$",
    neighborhood: "gracia",
    imageUrl: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Palo Alto Market Poblenou",
    placeType: "activity",
    address: "Carrer dels Pellaires 30-38, 08019 Barcelona",
    latitude: "41.4040000",
    longitude: "2.2005000",
    localRating: "4.7",
    touristMentions: 120,
    localMentions: 2000,
    gemScore: 78,
    discoveryStatus: "emerging",
    description: "A curated design and artisan market inside a converted industrial compound in Poblenou. Runs the first weekend of every month — jewelry, ceramics, furniture, food trucks, and live music.",
    whyLocalsLoveIt: "The best-edited market in Barcelona. Real designers, not souvenir tat. The food trucks are excellent.",
    bestFor: ["shopping", "design", "weekend", "gifts"],
    priceRange: "$",
    neighborhood: "poblenou",
    imageUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Hotel Neri Le Born",
    placeType: "hotel",
    address: "Carrer de Sant Sever 5, 08002 Barcelona",
    latitude: "41.3834000",
    longitude: "2.1748000",
    localRating: "4.8",
    touristMentions: 200,
    localMentions: 500,
    gemScore: 80,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A 22-room boutique hotel inside a 12th-century palace in the Gothic Quarter, facing the shaded Plaça de Sant Felip Neri. The rooftop terrace is one of Barcelona's most serene spots.",
    whyLocalsLoveIt: "The plaza below has a fountain and shade — it's where locals read on Sunday afternoons. The hotel feels like a private palazzo.",
    bestFor: ["boutique stay", "couples", "history lovers", "quiet"],
    priceRange: "$$$",
    neighborhood: "el-born",
    imageUrl: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Sagrada Família Glory Facade at Dawn",
    placeType: "scenic",
    address: "Carrer de Mallorca 401, 08013 Barcelona",
    latitude: "41.4036000",
    longitude: "2.1744000",
    localRating: "4.9",
    touristMentions: 800,
    localMentions: 2000,
    gemScore: 83,
    discoveryStatus: "emerging",
    description: "The south-facing Glory Facade catches the first morning light while the rest of Barcelona sleeps. At 7am, the golden stone glows with no crowd blocking the composition.",
    whyLocalsLoveIt: "Every local knows the tourists queue at the Nativity Facade. The Glory side at dawn gives you the cathedral to yourself.",
    bestFor: ["photography", "architecture", "dawn", "golden hour"],
    priceRange: "$",
    neighborhood: "poblenou",
    imageUrl: "https://images.unsplash.com/photo-1583779457094-ab6f77f7bf57?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Plaça del Sol Gràcia Terrace",
    placeType: "attraction",
    address: "Plaça del Sol, 08012 Barcelona",
    latitude: "41.4060000",
    longitude: "2.1571000",
    localRating: "4.7",
    touristMentions: 75,
    localMentions: 1800,
    gemScore: 77,
    discoveryStatus: "hidden",
    daysUntilMainstream: 220,
    description: "The beating heart of the Gràcia neighbourhood — a square ringed with cafes, ice-cream bars, and locals on folding chairs who seem to have nowhere better to be. Best at aperitivo hour.",
    whyLocalsLoveIt: "This is the neighbourhood square every tourist city claims to have but rarely does. The terrace at Bar Canigó is the best seat in Barcelona.",
    bestFor: ["aperitivo", "people watching", "local atmosphere", "evening"],
    priceRange: "$",
    neighborhood: "gracia",
    imageUrl: "https://images.unsplash.com/photo-1559628233-c0b7f60bed7d?auto=format&fit=crop&w=800&q=80",
  },

  // ── BALI (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ───────────────────────
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Warung Babi Guling Ibu Oka",
    placeType: "restaurant",
    address: "Jl. Tegal Sari No.2, Ubud, Gianyar",
    latitude: "-8.5062000",
    longitude: "115.2629000",
    localRating: "4.8",
    touristMentions: 250,
    localMentions: 2000,
    gemScore: 81,
    discoveryStatus: "emerging",
    description: "The legendary whole-roasted suckling pig (babi guling) restaurant in Ubud. The crispy skin, spiced minced pork, and blood sausage set the gold standard. Sells out by 1pm.",
    whyLocalsLoveIt: "Every Balinese will tell you this is the best babi guling on the island. Arrive at 11am and order the full set.",
    bestFor: ["local cuisine", "lunch", "foodie", "cultural experience"],
    priceRange: "$",
    neighborhood: "ubud",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Shelter Coffee Canggu",
    placeType: "cafe",
    address: "Jl. Pantai Batu Mejan, Canggu, Badung",
    latitude: "-8.6476000",
    longitude: "115.1324000",
    localRating: "4.7",
    touristMentions: 180,
    localMentions: 1200,
    gemScore: 76,
    discoveryStatus: "emerging",
    description: "A multi-story open-air coffee and coworking space with paddy field views. Single-origin Flores and Toraja beans brewed meticulously by trained baristas with a calm, non-tourist atmosphere.",
    whyLocalsLoveIt: "The Bali expat community's office. The cold brew and avocado toast are executed better here than anywhere on the island.",
    bestFor: ["coffee", "coworking", "slow mornings", "digital nomad"],
    priceRange: "$",
    neighborhood: "canggu",
    imageUrl: "https://images.unsplash.com/photo-1517992130453-c2e6f0b1b5e4?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Pasar Badung Traditional Market",
    placeType: "food",
    address: "Jl. Sulawesi, Denpasar",
    latitude: "-8.6584000",
    longitude: "115.2171000",
    localRating: "4.6",
    touristMentions: 70,
    localMentions: 1800,
    gemScore: 74,
    discoveryStatus: "hidden",
    daysUntilMainstream: 200,
    description: "Bali's largest traditional market — four floors of exotic spices, temple offerings, tropical fruit, and satay vendors. The early morning is a festival of colour and smell that no hotel buffet can match.",
    whyLocalsLoveIt: "Balinese housewives shop here at 5am. The chaos is orderly once you understand it — and the tamarind iced drinks are incomparable.",
    bestFor: ["spice shopping", "local culture", "photography", "early morning"],
    priceRange: "$",
    neighborhood: "kuta",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Jatiluwih Rice Terraces Sunrise Walk",
    placeType: "scenic",
    address: "Jatiluwih, Tabanan Regency, Bali",
    latitude: "-8.3668000",
    longitude: "115.1290000",
    localRating: "4.9",
    touristMentions: 300,
    localMentions: 1500,
    gemScore: 88,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "A UNESCO-listed subak irrigation system 700m above sea level — the most photogenic rice terraces in Bali, far from the Tegallalang crowds. Sunrise turns the paddies a hundred shades of green.",
    whyLocalsLoveIt: "Tegallalang has become a selfie queue. Jatiluwih is what Bali's rice terraces should feel like — panoramic, working, and peaceful.",
    bestFor: ["photography", "hiking", "sunrise", "UNESCO site"],
    priceRange: "$",
    neighborhood: "ubud",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Pura Lempuyang Temple Gate",
    placeType: "viewpoint",
    address: "Pura Lempuyang, Karangasem Regency, Bali",
    latitude: "-8.3925000",
    longitude: "115.6316000",
    localRating: "4.9",
    touristMentions: 600,
    localMentions: 2000,
    gemScore: 85,
    discoveryStatus: "emerging",
    description: "The 'Gates of Heaven' split gate framing Mount Agung is Bali's most iconic composition. Arrive before 7am for an empty gate and natural light before the queue forms.",
    whyLocalsLoveIt: "The reflection pool photo is a mirror trick but the real gate with Agung framed behind it needs no tricks — just an early alarm.",
    bestFor: ["photography", "temple visit", "dawn", "iconic shot"],
    priceRange: "$",
    neighborhood: "sanur",
    imageUrl: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Komaneka at Bisma Ubud",
    placeType: "hotel",
    address: "Jl. Bisma, Ubud, Gianyar, Bali",
    latitude: "-8.5090000",
    longitude: "115.2573000",
    localRating: "4.9",
    touristMentions: 160,
    localMentions: 450,
    gemScore: 84,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A cliff-edge boutique resort in Ubud's ravine with infinity pool views over the jungle canopy and Wos River valley. Balinese pavilion architecture, art collection, and farm-to-table restaurant.",
    whyLocalsLoveIt: "The jungle breakfast with mist rising from the valley below is one of Bali's finest morning experiences. Worth the splurge.",
    bestFor: ["luxury stay", "honeymoon", "jungle views", "pool"],
    priceRange: "$$$$",
    neighborhood: "ubud",
    imageUrl: "https://images.unsplash.com/photo-1540541338537-ef5c5ee16535?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Tanah Lot Temple at Dusk",
    placeType: "attraction",
    address: "Tanah Lot, Tabanan Regency, Bali",
    latitude: "-8.6215000",
    longitude: "115.0867000",
    localRating: "4.8",
    touristMentions: 700,
    localMentions: 2500,
    gemScore: 80,
    discoveryStatus: "emerging",
    description: "A 16th-century Hindu sea temple perched on a rock stack in the Indian Ocean — dramatically lit at sunset when the tide rolls in. The surrounding sea snakes are considered sacred guardians.",
    whyLocalsLoveIt: "Come at low tide to walk to the temple base, then stay for the sunset on the clifftop. The crowd thins rapidly after the sun sets.",
    bestFor: ["temple visit", "sunset", "photography", "cultural experience"],
    priceRange: "$",
    neighborhood: "seminyak",
    imageUrl: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Semara Ratih Dance Performance",
    placeType: "activity",
    address: "Jl. Raya Kedewatan, Ubud, Gianyar",
    latitude: "-8.4921000",
    longitude: "115.2481000",
    localRating: "4.9",
    touristMentions: 130,
    localMentions: 900,
    gemScore: 82,
    discoveryStatus: "hidden",
    daysUntilMainstream: 250,
    description: "A small family-run performance space in the forest edge of Ubud presenting traditional Kecak, Legong, and Barong dances by master performers — none of the commercial staging of the palace shows.",
    whyLocalsLoveIt: "The performers here are the teachers that all the palace show dancers learned from. An intimate window into Balinese sacred performance.",
    bestFor: ["cultural performance", "traditional dance", "evening", "authentic experience"],
    priceRange: "$$",
    neighborhood: "ubud",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
  },

  // ── NEW YORK (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ───────────────────
  {
    city: "New York",
    country: "USA",
    placeName: "Di Fara Pizza Brooklyn",
    placeType: "restaurant",
    address: "1424 Avenue J, Brooklyn, NY 11230",
    latitude: "40.6249000",
    longitude: "-73.9617000",
    localRating: "4.9",
    touristMentions: 300,
    localMentions: 3500,
    gemScore: 89,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "Dom DeMarco's legendary Midwood pizzeria — one man making every pizza by hand since 1964. The square Sicilian slice with basil scissors fresh from a potted plant is New York's best pizza.",
    whyLocalsLoveIt: "Dom is in his 80s and still makes every pie. There is a wait, there is no ambiance, and it is worth every minute.",
    bestFor: ["pizza", "New York classics", "foodie", "lunch"],
    priceRange: "$",
    neighborhood: "williamsburg",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "Russ and Daughters Cafe",
    placeType: "cafe",
    address: "127 Orchard Street, New York, NY 10002",
    latitude: "40.7200000",
    longitude: "-73.9878000",
    localRating: "4.8",
    touristMentions: 250,
    localMentions: 2800,
    gemScore: 84,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "The sit-down cafe extension of the 1914 appetizing institution on Houston Street. The Super Heebster bagel — whitefish salad, horseradish cream cheese, wasabi flying fish roe — is New York's greatest bagel.",
    whyLocalsLoveIt: "Four generations of Jewish-American food culture in one room. The smoked salmon flight makes Sunday brunch a ceremony.",
    bestFor: ["brunch", "bagels", "NYC institution", "Jewish deli culture"],
    priceRange: "$$",
    neighborhood: "lower-east-side",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "Smorgasburg Williamsburg",
    placeType: "food",
    address: "East River State Park, Williamsburg, Brooklyn",
    latitude: "40.7131000",
    longitude: "-73.9631000",
    localRating: "4.7",
    touristMentions: 500,
    localMentions: 3000,
    gemScore: 80,
    discoveryStatus: "emerging",
    description: "A 100-vendor outdoor food market every Saturday (April–October) on the Williamsburg waterfront with Manhattan skyline views. Everything is original — no chains, no repeats, all made that day.",
    whyLocalsLoveIt: "The ramen burger was invented here. New vendors debut every season and Brooklynites track the lineup obsessively.",
    bestFor: ["street food", "Saturday morning", "food discovery", "Manhattan views"],
    priceRange: "$",
    neighborhood: "williamsburg",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "The Cloisters Fort Tryon Park",
    placeType: "attraction",
    address: "99 Margaret Corbin Drive, New York, NY 10040",
    latitude: "40.8647000",
    longitude: "-73.9317000",
    localRating: "4.9",
    touristMentions: 200,
    localMentions: 1800,
    gemScore: 86,
    discoveryStatus: "hidden",
    daysUntilMainstream: 400,
    description: "A medieval castle transplanted to upper Manhattan housing the Met's collection of medieval art and architecture. The Hudson River views from the gardens are as good as any in New York — and rarely crowded.",
    whyLocalsLoveIt: "The Unicorn Tapestries alone justify the trip. The gardens in May smell of medieval herbs. Most New Yorkers never make it here.",
    bestFor: ["museum", "art", "gardens", "Hudson views", "hidden NYC"],
    priceRange: "$",
    neighborhood: "washington-heights",
    imageUrl: "https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "High Line Chelsea at Sunset",
    placeType: "scenic",
    address: "High Line, Chelsea, New York, NY 10011",
    latitude: "40.7480000",
    longitude: "-74.0048000",
    localRating: "4.8",
    touristMentions: 800,
    localMentions: 3500,
    gemScore: 82,
    discoveryStatus: "emerging",
    description: "The 1.45-mile elevated park on a former freight rail line through Chelsea and Hell's Kitchen. Sunset from the 10th Avenue Square overlook — when the Hudson turns gold and the city lights come on — is one of NYC's best free views.",
    whyLocalsLoveIt: "Go on a weekday at 6pm. The tourist crowd has thinned and the Chelsea gallery-goers take over. The garden plantings in autumn are particularly beautiful.",
    bestFor: ["photography", "sunset", "urban gardens", "evening walk"],
    priceRange: "$",
    neighborhood: "chelsea",
    imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "DUMBO Brooklyn Bridge Viewpoint",
    placeType: "viewpoint",
    address: "Washington Street between Front and Water, DUMBO, Brooklyn",
    latitude: "40.7033000",
    longitude: "-73.9897000",
    localRating: "4.9",
    touristMentions: 700,
    localMentions: 2500,
    gemScore: 85,
    discoveryStatus: "emerging",
    description: "The Manhattan Bridge perfectly framed down Washington Street with the Brooklyn Bridge in the background — arguably the most photographed street perspective in New York. Best at blue hour when the bridge lights come on.",
    whyLocalsLoveIt: "It's a short walk from the F/A train at York Street. Go at 5:30am on a weekend and you'll have the shot without 50 people in frame.",
    bestFor: ["photography", "architecture", "golden hour", "iconic NYC shot"],
    priceRange: "$",
    neighborhood: "dumbo",
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "The Jane Hotel Greenwich Village",
    placeType: "hotel",
    address: "113 Jane Street, New York, NY 10014",
    latitude: "40.7357000",
    longitude: "-74.0094000",
    localRating: "4.6",
    touristMentions: 220,
    localMentions: 600,
    gemScore: 76,
    discoveryStatus: "hidden",
    daysUntilMainstream: 200,
    description: "A 1908 maritime hotel in the West Village — Titanic survivors stayed here. Cabin rooms are tiny but beautifully designed, and the Jane Ballroom hosts some of Manhattan's best underground parties.",
    whyLocalsLoveIt: "The ballroom and rooftop are fixtures of NYC's creative scene. The cabin rooms make you feel like you're bunking on a luxury steamship.",
    bestFor: ["boutique stay", "West Village location", "nightlife", "unique experience"],
    priceRange: "$$",
    neighborhood: "greenwich-village",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "Jazz at the Village Vanguard",
    placeType: "activity",
    address: "178 7th Avenue South, New York, NY 10014",
    latitude: "40.7338000",
    longitude: "-74.0007000",
    localRating: "4.9",
    touristMentions: 300,
    localMentions: 1800,
    gemScore: 88,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "The most important jazz club in the world — a wedge-shaped basement that has hosted Miles Davis, Coltrane, and Bill Evans since 1935. The Monday night Vanguard Jazz Orchestra residency has run for 50+ years.",
    whyLocalsLoveIt: "You are listening to jazz on the exact stage where the recordings you grew up with were made. Nothing in New York touches this for music history.",
    bestFor: ["jazz", "live music", "New York classics", "evening"],
    priceRange: "$$",
    neighborhood: "greenwich-village",
    imageUrl: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?auto=format&fit=crop&w=800&q=80",
  },

  // ── ROME (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ───────────────────────
  {
    city: "Rome",
    country: "Italy",
    placeName: "Da Enzo al 29 Trastevere",
    placeType: "restaurant",
    address: "Via dei Vascellari 29, 00153 Rome",
    latitude: "41.8876000",
    longitude: "12.4699000",
    localRating: "4.8",
    touristMentions: 200,
    localMentions: 2500,
    gemScore: 83,
    discoveryStatus: "hidden",
    daysUntilMainstream: 250,
    description: "A no-reservations Trastevere trattoria with checkered tablecloths, handwritten menus, and Roman classics done without compromise. The cacio e pepe and coda alla vaccinara are definitive versions.",
    whyLocalsLoveIt: "This is where Rome's restaurant industry eats on their nights off. Order the house wine, the seasonal artichokes, and whatever the specials board says.",
    bestFor: ["Roman cuisine", "pasta", "traditional trattoria", "dinner"],
    priceRange: "$$",
    neighborhood: "trastevere",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Flavio al Velavevodetto Testaccio",
    placeType: "dining",
    address: "Via di Monte Testaccio 97, 00153 Rome",
    latitude: "41.8755000",
    longitude: "12.4773000",
    localRating: "4.7",
    touristMentions: 120,
    localMentions: 1800,
    gemScore: 80,
    discoveryStatus: "hidden",
    daysUntilMainstream: 280,
    description: "Built into the side of Monte Testaccio — literally a 35-metre hill of ancient Roman amphora sherds — this trattoria serves cucina romana povera at its finest. The rigatoni con pajata is a Roman rite of passage.",
    whyLocalsLoveIt: "The dining room has ancient ceramic sherds embedded in the wall. The menu is offal-forward, seasonal, and without concession to tourist tastes.",
    bestFor: ["offal cuisine", "Roman food culture", "historic setting", "dinner"],
    priceRange: "$$",
    neighborhood: "testaccio",
    imageUrl: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Mercato Testaccio Saturday Morning",
    placeType: "food",
    address: "Via Beniamino Franklin, 00153 Rome",
    latitude: "41.8760000",
    longitude: "12.4743000",
    localRating: "4.8",
    touristMentions: 100,
    localMentions: 2200,
    gemScore: 82,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "Rome's best covered market — a modern building replacing the beloved old market, packed with local producers selling Roman artichokes, porchetta, fresh pasta, and sheep ricotta so fresh it is still warm.",
    whyLocalsLoveIt: "The porchetta sandwiches here are the benchmark for all others. Go on Saturday when the seasonal produce sellers set up outside.",
    bestFor: ["food shopping", "local culture", "morning", "picnic"],
    priceRange: "$",
    neighborhood: "testaccio",
    imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Centrale Montemartini Museum",
    placeType: "attraction",
    address: "Via Ostiense 106, 00154 Rome",
    latitude: "41.8665000",
    longitude: "12.4802000",
    localRating: "4.9",
    touristMentions: 90,
    localMentions: 1200,
    gemScore: 87,
    discoveryStatus: "hidden",
    daysUntilMainstream: 400,
    description: "Ancient Roman sculptures displayed inside a 1912 electricity generating station — marble gods among industrial turbines and boiler rooms. One of Rome's most visually arresting and least-visited museums.",
    whyLocalsLoveIt: "The contrast of classical sculpture against industrial machinery is unlike anything in Rome's crowded museum circuit. Rarely has more than 50 visitors.",
    bestFor: ["museum", "art", "photography", "industrial design"],
    priceRange: "$",
    neighborhood: "ostiense",
    imageUrl: "https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Pigneto Aperitivo Strip",
    placeType: "activity",
    address: "Via del Pigneto, 00176 Rome",
    latitude: "41.8887000",
    longitude: "12.5204000",
    localRating: "4.7",
    touristMentions: 60,
    localMentions: 2000,
    gemScore: 78,
    discoveryStatus: "hidden",
    daysUntilMainstream: 280,
    description: "The pedestrian stretch of Via del Pigneto at aperitivo hour (6–9pm) is Rome's best kept secret — a street once populated by Pasolini's films now lined with indie bars offering €5 Negronis with generous snacks.",
    whyLocalsLoveIt: "Zero tourists, maximum Romans. This is where Rome's art school crowd, film industry workers, and neighbourhood old-timers converge at dusk.",
    bestFor: ["aperitivo", "nightlife", "local culture", "Negroni"],
    priceRange: "$",
    neighborhood: "pigneto",
    imageUrl: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Portrait Roma Hotel Prati",
    placeType: "hotel",
    address: "Via Bocca di Leone 23, 00187 Rome",
    latitude: "41.9055000",
    longitude: "12.4610000",
    localRating: "4.9",
    touristMentions: 180,
    localMentions: 400,
    gemScore: 83,
    discoveryStatus: "hidden",
    daysUntilMainstream: 350,
    description: "A 14-suite palazzo hotel on one of Rome's most elegant shopping streets, managed by the Ferragamo family. The rooftop with Castel Sant'Angelo and Vatican views is one of Rome's finest.",
    whyLocalsLoveIt: "The Ferragamo touch means every detail is considered — linens, breakfast, art. The bar terrace facing the Tiber at sunset is a local event.",
    bestFor: ["luxury stay", "couples", "rooftop views", "boutique"],
    priceRange: "$$$$",
    neighborhood: "prati",
    imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe2f5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Trastevere at Dawn Before the Tourists",
    placeType: "scenic",
    address: "Piazza di Santa Maria in Trastevere, 00153 Rome",
    latitude: "41.8895000",
    longitude: "12.4694000",
    localRating: "4.9",
    touristMentions: 500,
    localMentions: 2800,
    gemScore: 86,
    discoveryStatus: "hidden",
    daysUntilMainstream: 350,
    description: "The cobblestone neighbourhood of Trastevere at 6am is a different city — damp streets, cats, the golden mosaic of Santa Maria basilica glowing before the day's first Mass. Photography impossible to replicate by afternoon.",
    whyLocalsLoveIt: "Rome is a different city before 8am. The ochre light on the basilica mosaic in the deserted piazza is the city's finest secret visual.",
    bestFor: ["photography", "dawn", "architecture", "quiet Rome"],
    priceRange: "$",
    neighborhood: "trastevere",
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Aventine Hill Orange Garden Keyhole",
    placeType: "viewpoint",
    address: "Piazza dei Cavalieri di Malta, 00153 Rome",
    latitude: "41.8817000",
    longitude: "12.4792000",
    localRating: "4.9",
    touristMentions: 250,
    localMentions: 1500,
    gemScore: 84,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A keyhole in the Knights of Malta priory gate on the Aventine Hill frames a perfect tunnel of cypress trees with St Peter's dome centred at the vanishing point. One of Rome's most secretive photo spots.",
    whyLocalsLoveIt: "The fact that you look through a keyhole at one of the world's most famous domes makes this absurdly and perfectly Roman. Queue is five minutes, not five hours.",
    bestFor: ["photography", "architecture", "hidden Rome", "iconic shot"],
    priceRange: "$",
    neighborhood: "trastevere",
    imageUrl: "https://images.unsplash.com/photo-1529154166925-574a0236a4f4?auto=format&fit=crop&w=800&q=80",
  },

  // ── LONDON (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ─────────────────────
  {
    city: "London",
    country: "United Kingdom",
    placeName: "St John Bread and Wine Spitalfields",
    placeType: "restaurant",
    address: "94-96 Commercial Street, London E1 6LZ",
    latitude: "51.5178000",
    longitude: "-0.0758000",
    localRating: "4.8",
    touristMentions: 150,
    localMentions: 2000,
    gemScore: 82,
    discoveryStatus: "hidden",
    daysUntilMainstream: 240,
    description: "The east-end sibling of Fergus Henderson's nose-to-tail institution — same whole-animal ethos, simpler format. Bone marrow on toast, eccles cakes with Lancashire cheese, and a wine list of curious naturals.",
    whyLocalsLoveIt: "This is where London's chefs eat breakfast. The genius is in simplicity — perfect ingredients, zero technique fuss, honest bread.",
    bestFor: ["nose-to-tail", "brunch", "London classics", "foodie"],
    priceRange: "$$",
    neighborhood: "shoreditch",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Borough Market Thursday Lunch",
    placeType: "food",
    address: "8 Southwark Street, London SE1 1TL",
    latitude: "51.5054000",
    longitude: "-0.0910000",
    localRating: "4.7",
    touristMentions: 600,
    localMentions: 3000,
    gemScore: 79,
    discoveryStatus: "emerging",
    description: "London's oldest food market has weekend crowds, but Thursday lunch is the locals' time — fewer tourists, the same quality producers, and the Brindisa chorizo sandwich and Monmouth coffee still in full operation.",
    whyLocalsLoveIt: "The Gujarati vegetarian stall and the Roast pork roll from HG Walter are food industry secrets. Arrive at 12:30 when office workers thin out.",
    bestFor: ["street food", "lunch", "London food culture", "market"],
    priceRange: "$",
    neighborhood: "south-bank",
    imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Rochelle Canteen Shoreditch",
    placeType: "dining",
    address: "16 Playground Gardens, London E2 7FA",
    latitude: "51.5258000",
    longitude: "-0.0774000",
    localRating: "4.8",
    touristMentions: 80,
    localMentions: 1500,
    gemScore: 81,
    discoveryStatus: "hidden",
    daysUntilMainstream: 280,
    description: "A canteen inside a converted bike shed in a former Victorian school — the menu changes twice daily, British seasonal ingredients, and a garden terrace that feels like a secret. Ring the bell to enter.",
    whyLocalsLoveIt: "The lunch reservation list has a long wait because this is where London's creative industry spends its lunch hour. The daily menu handwriting is the best food journalism in the city.",
    bestFor: ["British seasonal", "creative industry crowd", "garden", "lunch"],
    priceRange: "$$",
    neighborhood: "shoreditch",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Columbia Road Flower Market Sunday",
    placeType: "activity",
    address: "Columbia Road, London E2 7RG",
    latitude: "51.5298000",
    longitude: "-0.0758000",
    localRating: "4.9",
    touristMentions: 350,
    localMentions: 2800,
    gemScore: 85,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "A Victorian street transforms every Sunday morning into London's most colourful flower and plant market — cockney barrow boys shouting prices while East End galleries and brunch spots open their doors alongside.",
    whyLocalsLoveIt: "The 8am plant deals before tourists arrive are the best. The sellers' patter is performance art. The Dutch House cafe does the best fry-up in Shoreditch.",
    bestFor: ["Sunday morning", "photography", "plants", "local culture"],
    priceRange: "$",
    neighborhood: "shoreditch",
    imageUrl: "https://images.unsplash.com/photo-1490750967868-88df5691cc90?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Tate Modern Switch House Rooftop",
    placeType: "viewpoint",
    address: "Bankside, London SE1 9TG",
    latitude: "51.5076000",
    longitude: "-0.0994000",
    localRating: "4.8",
    touristMentions: 300,
    localMentions: 1800,
    gemScore: 83,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "The 10th-floor viewing terrace on the Blavatnik Building addition to Tate Modern gives a 360-degree Thames panorama — St Paul's, Tower Bridge, the City skyline — for free, no ticket required.",
    whyLocalsLoveIt: "Better views than the Shard without the £33 ticket. Take the lift to level 10 and walk out. Free, open until 10pm on Fridays and Saturdays.",
    bestFor: ["panoramic views", "photography", "free", "Thames vista"],
    priceRange: "$",
    neighborhood: "south-bank",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "The Zetter Townhouse Clerkenwell",
    placeType: "hotel",
    address: "49-50 St John's Square, London EC1V 4JJ",
    latitude: "51.5225000",
    longitude: "-0.1026000",
    localRating: "4.8",
    touristMentions: 170,
    localMentions: 450,
    gemScore: 80,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A 13-room boutique hotel in a Georgian townhouse around the Clerkenwell square — the cocktail lounge is London's most eccentric, with a taxidermy owl, mismatched antiques, and signature cocktails named after fictional aunts.",
    whyLocalsLoveIt: "The Zetter cocktail bar is a destination in itself. The rooms feel like staying in a very well-curated eccentric relative's home.",
    bestFor: ["boutique stay", "cocktails", "Clerkenwell location", "couples"],
    priceRange: "$$$",
    neighborhood: "shoreditch",
    imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe2f5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Portobello Road Notting Hill at Dawn",
    placeType: "scenic",
    address: "Portobello Road, London W11",
    latitude: "51.5144000",
    longitude: "-0.2047000",
    localRating: "4.8",
    touristMentions: 600,
    localMentions: 2200,
    gemScore: 82,
    discoveryStatus: "emerging",
    description: "The pastel-painted townhouses of Portobello Road photographed at 7am on a Friday — before the antique stalls set up and the crowds arrive — are the most recognisable street image in London.",
    whyLocalsLoveIt: "The colours are best in morning light, the street is empty, and you can see the architecture clearly. The antique dealers arriving to set up make a great candid.",
    bestFor: ["photography", "architecture", "Notting Hill", "dawn"],
    priceRange: "$",
    neighborhood: "notting-hill",
    imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Leake Street Graffiti Tunnel",
    placeType: "attraction",
    address: "Leake Street, Lambeth, London SE1",
    latitude: "51.5012000",
    longitude: "-0.1119000",
    localRating: "4.7",
    touristMentions: 180,
    localMentions: 1200,
    gemScore: 76,
    discoveryStatus: "hidden",
    daysUntilMainstream: 200,
    description: "A 300-metre tunnel under Waterloo Station where legal graffiti transforms the walls continuously — Banksy launched the tunnel in 2008. New works appear overnight and the entire canvas changes every few weeks.",
    whyLocalsLoveIt: "Come twice and you'll never see the same artwork. Skaters, urban artists, and photographers coexist in one of London's genuinely underground spaces.",
    bestFor: ["street art", "photography", "urban culture", "free"],
    priceRange: "$",
    neighborhood: "south-bank",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
  },
];

interface ServiceSeed {
  serviceName: string;
  shortDescription: string;
  description: string;
  serviceType: string;
  price: string;
  location: string;
  neighborhood: string;
  deliveryMethod: string;
  deliveryTimeframe: string;
  whatIncluded: string[];
  averageRating: string;
}

const CITY_SERVICES: ServiceSeed[] = [
  {
    serviceName: "Tokyo Hidden Bars Night Walk",
    shortDescription: "A guided evening through Golden Gai, Memory Lane, and secret basement bars",
    description: "Your local guide leads a 3-hour evening tour through Tokyo's most atmospheric bar districts — Golden Gai's 200 micro-bars, Omoide Yokocho (Memory Lane) yakitori under the Shinjuku tracks, and one or two secret spots known only to regulars. Includes first-round drinks at two venues.",
    serviceType: "experience",
    price: "89.00",
    location: "Tokyo, Japan",
    neighborhood: "shinjuku",
    deliveryMethod: "in_person",
    deliveryTimeframe: "3 hours (starts 8pm)",
    whatIncluded: ["3-hour guided walk", "First drinks at 2 venues", "Door-to-door bar tips", "Pocket neighborhood map", "Post-tour recommendations list"],
    averageRating: "4.9",
  },
  {
    serviceName: "Kyoto Dawn Temple Private Tour",
    shortDescription: "Beat the crowds with a private guide at Fushimi Inari and Gion at sunrise",
    description: "Begin at 5am at Fushimi Inari before the first tour buses arrive, then walk through the lantern-lit streets of Gion as geiko return from evening engagements. Finishes with a private matcha ceremony at a neighborhood tea room. Limited to 4 guests.",
    serviceType: "experience",
    price: "120.00",
    location: "Kyoto, Japan",
    neighborhood: "gion",
    deliveryMethod: "in_person",
    deliveryTimeframe: "4 hours (starts 5am)",
    whatIncluded: ["Private licensed guide", "Fushimi Inari summit hike", "Gion dawn walk", "Private matcha ceremony", "Transport between sites"],
    averageRating: "5.0",
  },
  {
    serviceName: "Paris Secret Passages and Natural Wine Tour",
    shortDescription: "Explore 19th-century covered arcades and taste cutting-edge natural wines",
    description: "A 3-hour afternoon experience combining Paris's hidden glass-roofed shopping arcades (Vivienne, Colbert, Jouffroy) with stops at two of the city's best natural-wine bars. Your guide is a sommelier and former Galeries Lafayette buyer.",
    serviceType: "experience",
    price: "95.00",
    location: "Paris, France",
    neighborhood: "le-marais",
    deliveryMethod: "in_person",
    deliveryTimeframe: "3 hours (2pm–5pm)",
    whatIncluded: ["Licensed sommelier guide", "Entry to 3 covered passages", "Natural wine tastings at 2 bars", "Cheese pairing", "Take-home wine map"],
    averageRating: "4.8",
  },
  {
    serviceName: "Barcelona Hidden Barrios Food and Vermouth Walk",
    shortDescription: "A tapas and vermouth crawl through Gràcia and El Born away from La Rambla",
    description: "A 3-hour morning food walk through two neighbourhoods tourists rarely explore properly — Gràcia's local market and bar scene and El Born's medieval cava bars. Includes vermouth at two family-run bars, pintxos at a Basque counter, and seasonal produce tasting at Mercat de l'Abaceria.",
    serviceType: "experience",
    price: "79.00",
    location: "Barcelona, Spain",
    neighborhood: "gracia",
    deliveryMethod: "in_person",
    deliveryTimeframe: "3 hours (10am–1pm)",
    whatIncluded: ["Local guide", "Vermouth at 2 bars", "Pintxos tasting", "Market visit and seasonal produce", "Neighbourhood map with recommendations"],
    averageRating: "4.9",
  },
  {
    serviceName: "Bali Sunrise Rice Terrace and Temple Private Tour",
    shortDescription: "Catch Jatiluwih terraces at dawn then Tanah Lot at dusk — Bali's full visual arc",
    description: "A full-day private tour combining a pre-dawn drive to Jatiluwih UNESCO rice terraces for sunrise photography, a traditional Balinese cooking class in a local family compound, and the Tanah Lot sea temple at golden hour. Maximum 4 guests.",
    serviceType: "experience",
    price: "149.00",
    location: "Bali, Indonesia",
    neighborhood: "ubud",
    deliveryMethod: "in_person",
    deliveryTimeframe: "Full day (5am–7pm)",
    whatIncluded: ["Private driver-guide", "Jatiluwih sunrise walk", "Balinese cooking class", "Lunch with host family", "Tanah Lot sunset entry"],
    averageRating: "5.0",
  },
  {
    serviceName: "New York Off-Grid Brooklyn Food Tour",
    shortDescription: "The Brooklyn food stops New York insiders actually visit — no tourist traps",
    description: "A 4-hour Saturday food tour starting at Smorgasburg on the Williamsburg waterfront, continuing through the neighbourhood for a Di Fara-style slice, a Russ & Daughters bagel in the Lower East Side, and finishing with craft beer at a Red Hook brewpub. Small groups of 6.",
    serviceType: "experience",
    price: "99.00",
    location: "New York, USA",
    neighborhood: "williamsburg",
    deliveryMethod: "in_person",
    deliveryTimeframe: "4 hours (10am–2pm, Saturdays)",
    whatIncluded: ["Local food guide", "Smorgasburg tastings", "Pizza and bagel stops", "Craft beer finish", "Neighbourhood food map"],
    averageRating: "4.8",
  },
  {
    serviceName: "Rome Trastevere and Testaccio Neighbourhood Food Walk",
    shortDescription: "Roman cucina povera and neighbourhood history in two of Rome's most authentic districts",
    description: "A 3.5-hour evening walk through Trastevere and Testaccio — the two neighbourhoods where Roman food culture has changed least. Includes Mercato Testaccio porchetta sandwich, supplì from a local bar, cacio e pepe tasting, and Aperol spritz in a piazza locals use daily.",
    serviceType: "experience",
    price: "85.00",
    location: "Rome, Italy",
    neighborhood: "trastevere",
    deliveryMethod: "in_person",
    deliveryTimeframe: "3.5 hours (5pm–8:30pm)",
    whatIncluded: ["Local Roman guide", "Mercato Testaccio visit", "Porchetta and supplì tastings", "Cacio e pepe stop", "Aperitivo in local piazza"],
    averageRating: "4.9",
  },
  {
    serviceName: "London East End Food and Street Art Morning Walk",
    shortDescription: "Shoreditch street art, Columbia Road flowers, and Brick Lane bagels before the crowds",
    description: "A 3-hour Sunday morning walk starting at the Columbia Road Flower Market at 8am, through Shoreditch's ever-changing street art murals, to Brick Lane for a salt beef bagel and coffee, finishing with a guided look at the Leake Street graffiti tunnel under Waterloo. Maximum 8 guests.",
    serviceType: "experience",
    price: "69.00",
    location: "London, United Kingdom",
    neighborhood: "shoreditch",
    deliveryMethod: "in_person",
    deliveryTimeframe: "3 hours (8am–11am, Sundays)",
    whatIncluded: ["Local guide", "Columbia Road Market", "Street art tour", "Brick Lane bagel", "Leake Street tunnel finish"],
    averageRating: "4.8",
  },
];

const SEED_PROVIDER_EMAIL = "seed-provider@traveloure.internal";

export async function seedPopularCitiesContent(): Promise<{ gems: number; services: number }> {
  let gemsCreated = 0;
  let servicesCreated = 0;

  // ── Hidden Gems ──────────────────────────────────────────────────────────
  for (const gem of HIDDEN_GEMS) {
    const existing = await db
      .select({ id: travelPulseHiddenGems.id })
      .from(travelPulseHiddenGems)
      .where(
        and(
          eq(travelPulseHiddenGems.city, gem.city),
          eq(travelPulseHiddenGems.placeName, gem.placeName),
        ),
      )
      .limit(1);

    if (existing.length > 0) {
      // Patch imageUrl on already-seeded rows that are missing a photo
      if (gem.imageUrl) {
        await db
          .update(travelPulseHiddenGems)
          .set({ imageUrl: gem.imageUrl })
          .where(
            and(
              eq(travelPulseHiddenGems.id, existing[0].id),
              or(
                isNull(travelPulseHiddenGems.imageUrl),
                eq(travelPulseHiddenGems.imageUrl, ""),
              ),
            ),
          );
      }
      continue;
    }

    await db.insert(travelPulseHiddenGems).values({
      city: gem.city,
      country: gem.country,
      placeName: gem.placeName,
      placeType: gem.placeType,
      address: gem.address,
      latitude: gem.latitude,
      longitude: gem.longitude,
      localRating: gem.localRating,
      touristMentions: gem.touristMentions,
      localMentions: gem.localMentions,
      gemScore: gem.gemScore,
      discoveryStatus: gem.discoveryStatus,
      daysUntilMainstream: gem.daysUntilMainstream,
      description: gem.description,
      whyLocalsLoveIt: gem.whyLocalsLoveIt,
      bestFor: gem.bestFor,
      priceRange: gem.priceRange,
      neighborhood: gem.neighborhood,
      imageUrl: gem.imageUrl,
      aiGenerated: false,
    });
    gemsCreated++;
  }

  // ── Provider Services ────────────────────────────────────────────────────
  // Resolve or create a deterministic seed provider user so this works in
  // completely fresh environments where no users have been created yet.
  let userId: string;

  const existingUser = await db
    .select({ id: users.id })
    .from(users)
    .where(eq(users.email, SEED_PROVIDER_EMAIL))
    .limit(1);

  if (existingUser.length > 0) {
    userId = existingUser[0].id;
  } else {
    const anyUser = await db.select({ id: users.id }).from(users).limit(1);
    if (anyUser.length > 0) {
      userId = anyUser[0].id;
    } else {
      const [created] = await db.insert(users).values({
        email: SEED_PROVIDER_EMAIL,
        firstName: "Traveloure",
        lastName: "Seed Provider",
        // Canonical vocabulary (shared/roles.ts): "service_provider" — the bare "provider"
        // this seed previously wrote is not a real stored role anywhere in the platform.
        role: "service_provider",
      }).returning({ id: users.id });
      userId = created.id;
    }
  }

  for (const svc of CITY_SERVICES) {
    const cityKeyword = svc.location.split(",")[0].trim();
    const existing = await db
      .select({ id: providerServices.id })
      .from(providerServices)
      .where(
        and(
          ilike(providerServices.location, `%${cityKeyword}%`),
          eq(providerServices.serviceName, svc.serviceName),
        ),
      )
      .limit(1);

    if (existing.length > 0) continue;

    // Migration-129 pattern applied at insert time: resolve the neighborhood
    // slug to its city_neighborhoods centroid so this row isn't born
    // NULL-coordinate (never fabricates — a miss just leaves it NULL).
    const centroid = await resolveNeighborhoodCentroid(svc.neighborhood);

    await db.insert(providerServices).values({
      userId,
      serviceName: svc.serviceName,
      shortDescription: svc.shortDescription,
      description: svc.description,
      serviceType: svc.serviceType,
      price: svc.price,
      location: svc.location,
      neighborhood: svc.neighborhood,
      deliveryMethod: svc.deliveryMethod,
      deliveryTimeframe: svc.deliveryTimeframe,
      whatIncluded: svc.whatIncluded,
      averageRating: svc.averageRating,
      status: "active",
      isFeatured: true,
      ...(centroid && {
        latitude: centroid.latitude,
        longitude: centroid.longitude,
        city: centroid.city,
        locationPrecision: centroid.locationPrecision,
      }),
    });
    servicesCreated++;
  }

  return { gems: gemsCreated, services: servicesCreated };
}

const isMainModule = import.meta.url === `file://${process.argv[1]}`;
if (isMainModule) {
  seedPopularCitiesContent()
    .then(({ gems, services }) => {
      console.log(`[popular-cities-content] Seed complete: ${gems} gems, ${services} services inserted.`);
      process.exit(0);
    })
    .catch((err) => {
      console.error("[popular-cities-content] Seed failed:", err);
      process.exit(1);
    });
}
