# Generated by Django 5.2.1 on 2025-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_localexpertform_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localexpertform',
            name='demo_password',
        ),
        migrations.AlterField(
            model_name='localexpertform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
