# Generated by Django 5.2.3 on 2026-04-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_localexpertform_short_bio_and_more'),
        ('authentication', '0009_user_is_service_provider_serviceproviderform'),
    ]

    operations = [
    ]
