# Generated by Django 5.2.1 on 2025-07-04 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_localexpertform'),
    ]

    operations = [
        migrations.AddField(
            model_name='localexpertform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localexpertform',
            name='demo_password',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localexpertform',
            name='status',
            field=models.CharField(default='pending'),
        ),
    ]
