# Generated by Django 5.2.1 on 2025-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_dob_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meal_preference',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_months',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='travel_style',
            field=models.JSONField(default=list),
        ),
    ]
