# Generated by Django 5.2.1 on 2025-07-04 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_meal_preference_user_preferred_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalExpertForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_in_city', models.IntegerField()),
                ('offer_service', models.BooleanField(default=False)),
                ('gov_id', models.FileField(upload_to='localExpert/')),
                ('travel_licence', models.FileField(upload_to='localExpert/')),
                ('instagram_link', models.TextField(blank=True, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('linkedin_link', models.TextField(blank=True, null=True)),
                ('services', models.JSONField(default=list)),
                ('service_availability', models.IntegerField(default=15)),
                ('price_expectation', models.IntegerField()),
                ('confirm_age', models.BooleanField(default=False)),
                ('t_and_c', models.BooleanField(default=False)),
                ('partnership', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
