// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-plancard/ActivityDetailPage.tsx": () => import("../components/mockups/dashboard-plancard/ActivityDetailPage.tsx"),
  "./components/mockups/dashboard-plancard/ExpertChatPage.tsx": () => import("../components/mockups/dashboard-plancard/ExpertChatPage.tsx"),
  "./components/mockups/dashboard-plancard/FullItineraryPage.tsx": () => import("../components/mockups/dashboard-plancard/FullItineraryPage.tsx"),
  "./components/mockups/dashboard-plancard/MapFullPage.tsx": () => import("../components/mockups/dashboard-plancard/MapFullPage.tsx"),
  "./components/mockups/dashboard-plancard/PlanCardFinal.tsx": () => import("../components/mockups/dashboard-plancard/PlanCardFinal.tsx"),
  "./components/mockups/dashboard-plancard/ReviewChangesPage.tsx": () => import("../components/mockups/dashboard-plancard/ReviewChangesPage.tsx"),
  "./components/mockups/dashboard-plancard/ServicesPage.tsx": () => import("../components/mockups/dashboard-plancard/ServicesPage.tsx"),
  "./components/mockups/dashboard-plancard/TransportDetailPage.tsx": () => import("../components/mockups/dashboard-plancard/TransportDetailPage.tsx"),
  "./components/mockups/dashboard-plancard/TripStatsPage.tsx": () => import("../components/mockups/dashboard-plancard/TripStatsPage.tsx"),
  "./components/mockups/expert-card/ExpertCard.tsx": () => import("../components/mockups/expert-card/ExpertCard.tsx")
};
