-- Migration 214: property minimum stay (ruling 112 Q6 — DECISIONS.md ledger row 112).
--
-- WHAT + WHY. The ratified provider-console mock's property builder carries a "Minimum stay"
-- field; migration 211 (ledger row 102) deliberately scoped it out, and the Run-2 conformance
-- pass (docs/testing/PROVIDER_BATCH_EXERCISE_RUN2.md §6b) graded its absence a P2 BUILD-GAP.
-- Ruling 112 Q6 adopts the mock's field set. One column, nothing else:
--
--   min_stay_nights: integer, property/property_room rows only by convention (app-enforced —
--     the editor only renders it for property shapes; no DB CHECK, the migration-195/199/211
--     publish-trap posture). NULL = never captured (every pre-214 row) — never a guessed 1.
--
-- The stay-shaped cancellation BAND half of Q6 needs no schema: cancellation_policy_type
-- (migration 144) already exists — the property editor simply gains the select, and the copy
-- shown is the ENFORCED schedule from cancellation-policy.service.ts, never invented windows.
--
-- WRITE RAIL: rides the existing PATCH /api/provider/services (like migration 211's four —
-- not a money/identity/rate field, §14/§18/§19 do not apply).
-- PUBLISH-TRAP: additive nullable, no CHECK, DECLARED in shared/schema.ts in the same commit.
-- Idempotent.

ALTER TABLE provider_services ADD COLUMN IF NOT EXISTS min_stay_nights integer;
