-- 250_defer_travel_pulse_cities_unique_index.sql
--
-- Migration 249 restored the normalized city/country expression UNIQUE index
-- before its production-data prerequisite had been completed. Replit Publish
-- computes a schema diff; it does not run application-owned production data
-- cleanup before applying that diff. Production still has historical duplicate
-- normalized city/country pairs, so the index blocks every publish.
--
-- Defer database-level enforcement until a future approved production-data
-- operation has reconciled those rows. Application lookup paths remain the
-- current duplicate-prevention authority. This migration intentionally does
-- not modify production data.
DROP INDEX IF EXISTS travel_pulse_cities_city_country_unique;