#!/usr/bin/env tsx

/**
 * Popular Cities Content Seed
 *
 * Seeds hidden gems so the location feed is never empty in a fresh environment.
 * HIDDEN GEMS ONLY (ruling 117, §13): every entry is a REAL named place with real
 * coordinates — editorial content, the platform's own TravelPulse scoring vocabulary.
 * The former provider-services half (a fake bookable "seed provider" with fabricated
 * review averages) was REMOVED by ruling 117: marketplace supply is never seeded —
 * an empty service lane in a new market renders honestly and is the provider-
 * acquisition funnel, not a gap to paper over.
 *
 * Each city has gems covering all four feed categories:
 *   Eat  — placeType includes: restaurant | cafe | dining | food
 *   Do   — placeType includes: attraction | activity | temple | shrine | park
 *   Stay — placeType includes: hotel | ryokan | hostel
 *   Photo— placeType includes: viewpoint | scenic | photo spot | photography
 *
 * Neighborhood slugs match those in city-neighborhoods.seed.ts.
 *
 * Idempotent: skips rows whose (city, placeName) already exist.
 * Provider services: creates a deterministic seed provider user if none exist.
 *
 * Run standalone: `tsx server/seeds/popular-cities-content.seed.ts`
 */

import { db } from "../db";
import { travelPulseHiddenGems } from "@workspace/db";
import { and, eq, isNull, or } from "drizzle-orm";
import { logger } from "../infrastructure";

interface GemSeed {
  city: string;
  country: string;
  placeName: string;
  placeType: string;
  address?: string;
  latitude: string;
  longitude: string;
  localRating: string;
  touristMentions: number;
  localMentions: number;
  gemScore: number;
  discoveryStatus: string;
  daysUntilMainstream?: number;
  description: string;
  whyLocalsLoveIt: string;
  bestFor: string[];
  priceRange: string;
  neighborhood: string;
  imageUrl?: string;
}

const HIDDEN_GEMS: GemSeed[] = [
  // ── TOKYO (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ─────────────────────
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Kayaba Coffee",
    placeType: "cafe",
    address: "6-1-29 Yanaka, Taito City, Tokyo",
    latitude: "35.7234000",
    longitude: "139.7657000",
    localRating: "4.7",
    touristMentions: 120,
    localMentions: 890,
    gemScore: 82,
    discoveryStatus: "hidden",
    daysUntilMainstream: 180,
    description: "A beautifully preserved 1930s wooden coffee house in the Yanaka shitamachi. Famous for its thick tamago-sando egg sandwich and single-origin pour-over.",
    whyLocalsLoveIt: "Time-stands-still atmosphere, no Instagram crowds, and the best morning set in east Tokyo.",
    bestFor: ["slow mornings", "breakfast", "solo travel"],
    priceRange: "$",
    neighborhood: "yanaka",
    imageUrl: "https://images.unsplash.com/photo-1576618148400-f54bbd73ed4f?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Nakameguro Koukashita",
    placeType: "restaurant",
    address: "Under the Tokyu Toyoko Line, Meguro City, Tokyo",
    latitude: "35.6442000",
    longitude: "139.6979000",
    localRating: "4.6",
    touristMentions: 200,
    localMentions: 1500,
    gemScore: 74,
    discoveryStatus: "emerging",
    daysUntilMainstream: 90,
    description: "A curated strip of micro-restaurants, craft-beer bars, and coffee roasters built under the elevated rail line along the Meguro canal.",
    whyLocalsLoveIt: "Canal views, zero tourist traps, and genuinely creative chefs working tiny open kitchens.",
    bestFor: ["date night", "craft beer", "evening out"],
    priceRange: "$$",
    neighborhood: "nakameguro",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Asakusa Hoppy Street Yakitori",
    placeType: "dining",
    address: "Hoppy-dori, Asakusa, Taito City, Tokyo",
    latitude: "35.7146000",
    longitude: "139.7945000",
    localRating: "4.5",
    touristMentions: 300,
    localMentions: 1800,
    gemScore: 71,
    discoveryStatus: "emerging",
    daysUntilMainstream: 60,
    description: "A rowdy pedestrian street where Tokyo working-class culture has thrived since the post-war era. Plastic stools, cheap hoppy beer, and shichirin grilled skewers.",
    whyLocalsLoveIt: "Unpretentious, dirt cheap, and utterly authentic. The grilled chicken skewers here have been perfected over decades.",
    bestFor: ["budget dining", "local culture", "street food"],
    priceRange: "$",
    neighborhood: "asakusa",
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Golden Gai Late-Night Bars",
    placeType: "attraction",
    address: "Golden Gai, Kabukicho, Shinjuku City, Tokyo",
    latitude: "35.6940000",
    longitude: "139.7050000",
    localRating: "4.9",
    touristMentions: 500,
    localMentions: 3000,
    gemScore: 88,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "200+ micro-bars packed into six tiny alleyways. Each fits 6-8 people, has its own theme, and is run by a single bartender who often doubles as DJ.",
    whyLocalsLoveIt: "Nowhere else on earth feels like this after midnight. Each bar is a world unto itself.",
    bestFor: ["nightlife", "solo travel", "unique experience"],
    priceRange: "$$",
    neighborhood: "shinjuku",
    imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Disk Union Shimokitazawa",
    placeType: "activity",
    address: "2-25-8 Kitazawa, Setagaya City, Tokyo",
    latitude: "35.6617000",
    longitude: "139.6683000",
    localRating: "4.8",
    touristMentions: 85,
    localMentions: 1200,
    gemScore: 79,
    discoveryStatus: "hidden",
    daysUntilMainstream: 220,
    description: "Seven-floor vinyl heaven stacked with Japanese pressings, jazz, city pop, and rare imports. Each floor is a different genre — come prepared to stay for hours.",
    whyLocalsLoveIt: "Serious collectors come weekly. Late-70s Japanese city pop LPs go for a few hundred yen.",
    bestFor: ["music lovers", "rainy days", "unique souvenirs"],
    priceRange: "$",
    neighborhood: "shimokitazawa",
    imageUrl: "https://images.unsplash.com/photo-1494232410401-ad00d5433cfa?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Claska Hotel Meguro",
    placeType: "hotel",
    address: "1-3-18 Chuo-cho, Meguro City, Tokyo",
    latitude: "35.6425000",
    longitude: "139.7004000",
    localRating: "4.6",
    touristMentions: 180,
    localMentions: 600,
    gemScore: 72,
    discoveryStatus: "emerging",
    description: "A design-forward boutique hotel in a converted 1960s ryokan building. The Gallery shop on the ground floor is one of Tokyo's best curated design shops.",
    whyLocalsLoveIt: "The interiors are textbook Japanese minimal design. Locals come for the gallery even if they aren't staying.",
    bestFor: ["design lovers", "couples", "boutique stay"],
    priceRange: "$$$",
    neighborhood: "nakameguro",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Yanaka Cemetery Cherry Blossom Walk",
    placeType: "scenic",
    address: "7-5-24 Yanaka, Taito City, Tokyo",
    latitude: "35.7255000",
    longitude: "139.7633000",
    localRating: "4.8",
    touristMentions: 180,
    localMentions: 2200,
    gemScore: 81,
    discoveryStatus: "hidden",
    daysUntilMainstream: 250,
    description: "Yanaka Cemetery's main avenue becomes a canopy of sakura blossoms in late March — entirely free, almost entirely locals, and no crowds compared to Ueno or Shinjuku.",
    whyLocalsLoveIt: "The combination of ancient gravestones and sakura blossoms is uniquely Tokyo. Golden hour here is transcendent.",
    bestFor: ["photography", "cherry blossom season", "walking"],
    priceRange: "$",
    neighborhood: "yanaka",
    imageUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Tokyo",
    country: "Japan",
    placeName: "Nakameguro Canal Viewpoint at Dusk",
    placeType: "viewpoint",
    address: "Nakameguro, Meguro City, Tokyo",
    latitude: "35.6450000",
    longitude: "139.6990000",
    localRating: "4.9",
    touristMentions: 600,
    localMentions: 3500,
    gemScore: 84,
    discoveryStatus: "emerging",
    description: "The 2km canal walk glows copper at sunset as boutique café lights reflect off the water. The tree canopy forms tunnels best photographed 30 minutes before dark.",
    whyLocalsLoveIt: "One of Tokyo's best free photo spots at any season — the lantern glow in autumn is particularly stunning.",
    bestFor: ["photography", "evening walk", "golden hour"],
    priceRange: "$",
    neighborhood: "nakameguro",
    imageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=80",
  },

  // ── KYOTO (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ─────────────────────
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Ippodo Tea Kaboku Tearoom",
    placeType: "cafe",
    address: "52 Teramachi Nijo-agaru, Nakagyo Ward, Kyoto",
    latitude: "35.0156000",
    longitude: "135.7672000",
    localRating: "4.9",
    touristMentions: 150,
    localMentions: 2100,
    gemScore: 85,
    discoveryStatus: "hidden",
    daysUntilMainstream: 240,
    description: "Established in 1717, this is the definitive matcha source for Kyoto's tea masters. The adjoining Kaboku tearoom serves any tea from their range, brewed with precision.",
    whyLocalsLoveIt: "Serious tea culture, zero tourist kitsch. Staff guide you to the perfect sencha for your taste and budget.",
    bestFor: ["tea lovers", "cultural immersion", "quiet afternoon"],
    priceRange: "$$",
    neighborhood: "kawaramachi-sanjo",
    imageUrl: "https://images.unsplash.com/photo-1569144157591-c60f3f82f137?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Nishiki Market Side Alleys",
    placeType: "food",
    address: "Nishiki Market, Nakagyo Ward, Kyoto",
    latitude: "35.0052000",
    longitude: "135.7648000",
    localRating: "4.7",
    touristMentions: 800,
    localMentions: 3500,
    gemScore: 78,
    discoveryStatus: "emerging",
    description: "Kyoto's 'kitchen' market — 100+ stalls of pickled vegetables, fresh tofu, grilled skewers, and seasonal sweets. The perpendicular side alleys have the best value eating.",
    whyLocalsLoveIt: "Grandmothers still shop here for their daily pickles. The tsukemono variety is unmatched anywhere.",
    bestFor: ["food tasting", "local culture", "lunch"],
    priceRange: "$",
    neighborhood: "kawaramachi-sanjo",
    imageUrl: "https://images.unsplash.com/photo-1564419320461-6870880221ad?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Kanga-an Temple Shojin Ryori",
    placeType: "restaurant",
    address: "17 Miyanishicho, Kita Ward, Kyoto",
    latitude: "35.0454000",
    longitude: "135.7447000",
    localRating: "4.8",
    touristMentions: 60,
    localMentions: 480,
    gemScore: 86,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A 17th-century Zen temple offering shojin ryori Buddhist vegetarian cuisine in private tatami rooms overlooking a moss garden. Reservation weeks in advance required.",
    whyLocalsLoveIt: "The seasonally changing menu is sourced entirely from the temple's own garden. An experience impossible to replicate.",
    bestFor: ["fine dining", "vegetarian", "cultural immersion"],
    priceRange: "$$$",
    neighborhood: "nishijin",
    imageUrl: "https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Fushimi Inari Pre-Dawn Hike",
    placeType: "attraction",
    address: "68 Fukakusa Yabunouchicho, Fushimi Ward, Kyoto",
    latitude: "34.9671000",
    longitude: "135.7727000",
    localRating: "5.0",
    touristMentions: 2000,
    localMentions: 4000,
    gemScore: 92,
    discoveryStatus: "hidden",
    daysUntilMainstream: 730,
    description: "The 10,000 torii path is magical but overcrowded by 8am. Arriving at 4:30am means walking the full summit trail completely alone in mist and candlelight.",
    whyLocalsLoveIt: "Dawn at the summit is a genuinely spiritual experience. Most tourists only do the first 30 minutes.",
    bestFor: ["hiking", "spiritual experience", "avoiding crowds"],
    priceRange: "$",
    neighborhood: "fushimi",
    imageUrl: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Pontocho Alley Evening Stroll",
    placeType: "activity",
    address: "Pontocho, Nakagyo Ward, Kyoto",
    latitude: "35.0083000",
    longitude: "135.7707000",
    localRating: "4.8",
    touristMentions: 900,
    localMentions: 2800,
    gemScore: 80,
    discoveryStatus: "emerging",
    description: "A 500-metre stone alley running parallel to the Kamo River. In summer, restaurants extend kawayuka elevated platforms over the water for open-air dining.",
    whyLocalsLoveIt: "The pre-dinner golden hour with lanterns just lit and no crowds is the most photogenic moment in all Kyoto.",
    bestFor: ["evening walk", "summer dining", "atmosphere"],
    priceRange: "$$",
    neighborhood: "pontocho",
    imageUrl: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Yoshida Sanso Ryokan",
    placeType: "ryokan",
    address: "59-1 Yoshida Shimoadachi-cho, Sakyo Ward, Kyoto",
    latitude: "35.0267000",
    longitude: "135.7839000",
    localRating: "4.9",
    touristMentions: 95,
    localMentions: 520,
    gemScore: 88,
    discoveryStatus: "hidden",
    daysUntilMainstream: 400,
    description: "A converted 1932 Imperial guesthouse on the forested slopes of Mount Yoshida. Nine suites, a private garden, and multi-course kaiseki dinner served in your room.",
    whyLocalsLoveIt: "The Japanese imperial hospitality tradition is alive here. No-one rushes you, no-one under 18, pure Kyoto.",
    bestFor: ["luxury stay", "couples", "authentic ryokan"],
    priceRange: "$$$$",
    neighborhood: "higashiyama",
    imageUrl: "https://images.unsplash.com/photo-1548165892-cd6be85a7f69?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Fushimi Inari Torii Tunnel at Dawn",
    placeType: "viewpoint",
    address: "Fushimi Inari Taisha, Fushimi Ward, Kyoto",
    latitude: "34.9673000",
    longitude: "135.7729000",
    localRating: "5.0",
    touristMentions: 1500,
    localMentions: 3800,
    gemScore: 93,
    discoveryStatus: "hidden",
    daysUntilMainstream: 730,
    description: "The lower torii tunnel photographed empty at 5am, backlit by the first sun slicing through the orange gates. Arguably the best photo opportunity in all of Japan.",
    whyLocalsLoveIt: "By 9am this exact spot has 200 people queuing. At dawn it is yours alone and lit like a film set.",
    bestFor: ["photography", "dawn", "iconic shot"],
    priceRange: "$",
    neighborhood: "fushimi",
    imageUrl: "https://images.unsplash.com/photo-1580917922805-21d32edd27e3?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Kyoto",
    country: "Japan",
    placeName: "Philosopher's Path Canal in Autumn",
    placeType: "scenic",
    address: "Tetsugaku no Michi, Sakyo Ward, Kyoto",
    latitude: "35.0168000",
    longitude: "135.7940000",
    localRating: "4.7",
    touristMentions: 600,
    localMentions: 2000,
    gemScore: 75,
    discoveryStatus: "emerging",
    description: "The canal-side path connecting Nanzen-ji to Ginkaku-ji. Less visited in autumn than spring, the red maple canopy over the water is arguably more beautiful than sakura season.",
    whyLocalsLoveIt: "Autumn maples reflected in the still canal at 7am — one of Kyoto's secret great photos.",
    bestFor: ["photography", "autumn foliage", "walking", "golden hour"],
    priceRange: "$",
    neighborhood: "higashiyama",
    imageUrl: "https://images.unsplash.com/photo-1601823984263-6ec76b4c8aaf?auto=format&fit=crop&w=800&q=80",
  },

  // ── PARIS (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ─────────────────────
  {
    city: "Paris",
    country: "France",
    placeName: "Au Passage Natural Wine Bar",
    placeType: "restaurant",
    address: "1bis Passage Saint-Sebastien, 75011 Paris",
    latitude: "48.8605000",
    longitude: "2.3715000",
    localRating: "4.8",
    touristMentions: 120,
    localMentions: 1800,
    gemScore: 83,
    discoveryStatus: "hidden",
    daysUntilMainstream: 180,
    description: "A cult natural-wine bar and small plates restaurant hidden in a covered passage near Republique. The lamb neck croquettes and the wine list are the talk of Paris's chef community.",
    whyLocalsLoveIt: "Zero decor investment, maximum food and wine obsession. The chefs here go on to run Paris's hottest tables.",
    bestFor: ["natural wine", "small plates", "date night", "foodie"],
    priceRange: "$$",
    neighborhood: "bastille",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Marche d'Aligre Sunday Morning",
    placeType: "food",
    address: "Place d'Aligre, 75012 Paris",
    latitude: "48.8500000",
    longitude: "2.3740000",
    localRating: "4.8",
    touristMentions: 180,
    localMentions: 3200,
    gemScore: 84,
    discoveryStatus: "hidden",
    daysUntilMainstream: 200,
    description: "The most Parisian market in Paris — outdoor flea stalls from 7am Thursday to Sunday, surrounded by covered food halls with oysters, charcuterie, and cheese.",
    whyLocalsLoveIt: "Flea items for 2 euros that cost 50 in Le Marais. The Beauvau covered hall has the best oyster bar in the 12th.",
    bestFor: ["bargain hunting", "food tasting", "local culture", "morning"],
    priceRange: "$",
    neighborhood: "bastille",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Cafe de la Mairie Saint-Sulpice",
    placeType: "cafe",
    address: "8 Place Saint-Sulpice, 75006 Paris",
    latitude: "48.8506000",
    longitude: "2.3333000",
    localRating: "4.6",
    touristMentions: 90,
    localMentions: 1500,
    gemScore: 78,
    discoveryStatus: "hidden",
    daysUntilMainstream: 210,
    description: "An unchanged 1950s zinc-bar cafe facing the Saint-Sulpice fountain — Sontag, Perec, and Fitzgerald all drank here. Terrace seats at normal French cafe prices.",
    whyLocalsLoveIt: "The best people-watching terrace on the Left Bank. No gimmicks, perfect crepes, honest pricing.",
    bestFor: ["coffee", "writing", "people watching", "literary Paris"],
    priceRange: "$",
    neighborhood: "saint-germain",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Buttes-Chaumont Park",
    placeType: "park",
    address: "Parc des Buttes-Chaumont, 75019 Paris",
    latitude: "48.8788000",
    longitude: "2.3817000",
    localRating: "4.9",
    touristMentions: 250,
    localMentions: 4500,
    gemScore: 87,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "Paris's most dramatic park — a Victorian landscape with a rocky island temple, suspension bridge, and sweeping panoramas. Locals picnic here while tourists queue at the Eiffel Tower.",
    whyLocalsLoveIt: "The island temple view at golden hour is equal to any postcard Paris. Completely free and uncrowded.",
    bestFor: ["picnic", "families", "afternoon escape", "views"],
    priceRange: "$",
    neighborhood: "belleville",
    imageUrl: "https://images.unsplash.com/photo-1551918120-9739cb430c6d?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Coulee Verte Elevated Park",
    placeType: "attraction",
    address: "Promenade Plantee, 75012 Paris",
    latitude: "48.8485000",
    longitude: "2.3762000",
    localRating: "4.7",
    touristMentions: 200,
    localMentions: 2800,
    gemScore: 80,
    discoveryStatus: "hidden",
    daysUntilMainstream: 270,
    description: "The world's first elevated park, built on a 19th-century railway viaduct above the 12th arrondissement — predating New York's High Line by 15 years. Gardens and city views from 10m up.",
    whyLocalsLoveIt: "A green ribbon of calm above street noise. The viaduct arches below are now art galleries worth exploring too.",
    bestFor: ["walking", "urban exploration", "gardens"],
    priceRange: "$",
    neighborhood: "bastille",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Hotel du Petit Moulin Le Marais",
    placeType: "hotel",
    address: "29-31 Rue de Poitou, 75003 Paris",
    latitude: "48.8612000",
    longitude: "2.3597000",
    localRating: "4.7",
    touristMentions: 160,
    localMentions: 480,
    gemScore: 77,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A 17th-century bakery — the oldest in Paris — converted into a 17-room design hotel by Christian Lacroix. Every room has a different hand-painted design.",
    whyLocalsLoveIt: "The building's history and Lacroix's artistry combine in ways no chain hotel ever could. No two rooms are the same.",
    bestFor: ["design lovers", "couples", "boutique stay", "Le Marais"],
    priceRange: "$$$",
    neighborhood: "le-marais",
    imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe2f5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Buttes-Chaumont Temple de la Sibylle Viewpoint",
    placeType: "viewpoint",
    address: "Ile du Belveder, Parc des Buttes-Chaumont, 75019 Paris",
    latitude: "48.8800000",
    longitude: "2.3820000",
    localRating: "4.9",
    touristMentions: 180,
    localMentions: 3000,
    gemScore: 88,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "Standing on the island summit temple gives a 360-degree panorama across Paris's rooftops and the Sacre-Coeur on the horizon — a view locals protect fiercely from overexposure.",
    whyLocalsLoveIt: "Better Parisian skyline view than the Eiffel Tower, completely free, and 90% fewer tourists.",
    bestFor: ["photography", "panoramic views", "golden hour"],
    priceRange: "$",
    neighborhood: "belleville",
    imageUrl: "https://images.unsplash.com/photo-1431274172761-fca41d930114?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Paris",
    country: "France",
    placeName: "Montmartre Vineyard Clos Montmartre",
    placeType: "scenic",
    address: "Rue des Saules, 75018 Paris",
    latitude: "48.8876000",
    longitude: "2.3405000",
    localRating: "4.7",
    touristMentions: 300,
    localMentions: 1200,
    gemScore: 75,
    discoveryStatus: "emerging",
    description: "Paris's last working vineyard in the 18th arrondissement — 1,700 bottles of Pinot Noir per year. The October harvest festival is a neighbourhood institution.",
    whyLocalsLoveIt: "Standing in a vineyard looking over Paris rooftops is surreal and secret. The October fete is the best local party of the year.",
    bestFor: ["photography", "wine lovers", "autumn visit", "unique experience"],
    priceRange: "$",
    neighborhood: "montmartre",
    imageUrl: "https://images.unsplash.com/photo-1471919743851-c3efa5059c11?auto=format&fit=crop&w=800&q=80",
  },

  // ── BARCELONA (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ──────────────────
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Bar Calders El Born Vermouth",
    placeType: "cafe",
    address: "Carrer del Parlament 25, 08015 Barcelona",
    latitude: "41.3779000",
    longitude: "2.1631000",
    localRating: "4.7",
    touristMentions: 90,
    localMentions: 1400,
    gemScore: 79,
    discoveryStatus: "hidden",
    daysUntilMainstream: 200,
    description: "A corner bar in Sant Antoni where Barcelona's creative class gathers on Sunday mornings for vermut, boquerones, and olives. The terrace spills onto the pavement and the kitchen closes when it feels like it.",
    whyLocalsLoveIt: "The Sunday vermouth ritual here is as authentic as it gets — no tourist menus, just house vermut and the newspaper.",
    bestFor: ["brunch", "vermouth", "local culture", "weekend morning"],
    priceRange: "$",
    neighborhood: "el-raval",
    imageUrl: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "El Xampanyet Cava Bar",
    placeType: "restaurant",
    address: "Carrer de Montcada 22, 08003 Barcelona",
    latitude: "41.3844000",
    longitude: "2.1818000",
    localRating: "4.8",
    touristMentions: 180,
    localMentions: 2200,
    gemScore: 82,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A Catalan cava bar opened in 1929, still run by the same family, just metres from the Picasso Museum. House cava is poured from unlabelled bottles and house-made anchovies are the must-order.",
    whyLocalsLoveIt: "This is the real El Born, unchanged and unhurried. Go before the Picasso Museum crowd spills in at noon.",
    bestFor: ["cava tasting", "pintxos", "historic venue", "couple"],
    priceRange: "$",
    neighborhood: "el-born",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Mercat de l'Abaceria Gràcia",
    placeType: "food",
    address: "Travessera de Gràcia 186, 08012 Barcelona",
    latitude: "41.4058000",
    longitude: "2.1563000",
    localRating: "4.6",
    touristMentions: 60,
    localMentions: 1100,
    gemScore: 76,
    discoveryStatus: "hidden",
    daysUntilMainstream: 250,
    description: "A 19th-century iron market in Gràcia that locals fiercely protect from the La Boqueria crowds. Organic produce, local cheeses, wild mushrooms, and an honest neighbourhood bar inside.",
    whyLocalsLoveIt: "The best market in Barcelona for actual shopping. Stallholders know your name here — no performance for tourists.",
    bestFor: ["food shopping", "local culture", "morning", "picnic supplies"],
    priceRange: "$",
    neighborhood: "gracia",
    imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Bunkers del Carmel Sunset Viewpoint",
    placeType: "viewpoint",
    address: "Turó de la Rovira, 08032 Barcelona",
    latitude: "41.4180000",
    longitude: "2.1545000",
    localRating: "4.9",
    touristMentions: 400,
    localMentions: 3800,
    gemScore: 90,
    discoveryStatus: "hidden",
    daysUntilMainstream: 400,
    description: "The ruins of a Civil War anti-aircraft battery on Barcelona's highest accessible hill. A 360-degree city panorama — Sagrada Família, Tibidabo, the sea — that no paid viewpoint in the city rivals.",
    whyLocalsLoveIt: "Locals bring wine, blankets and guitars at sunset. The view is better than the Sagrada Família rooftop and completely free.",
    bestFor: ["photography", "sunset", "panoramic views", "picnic"],
    priceRange: "$",
    neighborhood: "gracia",
    imageUrl: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Palo Alto Market Poblenou",
    placeType: "activity",
    address: "Carrer dels Pellaires 30-38, 08019 Barcelona",
    latitude: "41.4040000",
    longitude: "2.2005000",
    localRating: "4.7",
    touristMentions: 120,
    localMentions: 2000,
    gemScore: 78,
    discoveryStatus: "emerging",
    description: "A curated design and artisan market inside a converted industrial compound in Poblenou. Runs the first weekend of every month — jewelry, ceramics, furniture, food trucks, and live music.",
    whyLocalsLoveIt: "The best-edited market in Barcelona. Real designers, not souvenir tat. The food trucks are excellent.",
    bestFor: ["shopping", "design", "weekend", "gifts"],
    priceRange: "$",
    neighborhood: "poblenou",
    imageUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Hotel Neri Le Born",
    placeType: "hotel",
    address: "Carrer de Sant Sever 5, 08002 Barcelona",
    latitude: "41.3834000",
    longitude: "2.1748000",
    localRating: "4.8",
    touristMentions: 200,
    localMentions: 500,
    gemScore: 80,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A 22-room boutique hotel inside a 12th-century palace in the Gothic Quarter, facing the shaded Plaça de Sant Felip Neri. The rooftop terrace is one of Barcelona's most serene spots.",
    whyLocalsLoveIt: "The plaza below has a fountain and shade — it's where locals read on Sunday afternoons. The hotel feels like a private palazzo.",
    bestFor: ["boutique stay", "couples", "history lovers", "quiet"],
    priceRange: "$$$",
    neighborhood: "el-born",
    imageUrl: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Sagrada Família Glory Facade at Dawn",
    placeType: "scenic",
    address: "Carrer de Mallorca 401, 08013 Barcelona",
    latitude: "41.4036000",
    longitude: "2.1744000",
    localRating: "4.9",
    touristMentions: 800,
    localMentions: 2000,
    gemScore: 83,
    discoveryStatus: "emerging",
    description: "The south-facing Glory Facade catches the first morning light while the rest of Barcelona sleeps. At 7am, the golden stone glows with no crowd blocking the composition.",
    whyLocalsLoveIt: "Every local knows the tourists queue at the Nativity Facade. The Glory side at dawn gives you the cathedral to yourself.",
    bestFor: ["photography", "architecture", "dawn", "golden hour"],
    priceRange: "$",
    neighborhood: "poblenou",
    imageUrl: "https://images.unsplash.com/photo-1583779457094-ab6f77f7bf57?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Barcelona",
    country: "Spain",
    placeName: "Plaça del Sol Gràcia Terrace",
    placeType: "attraction",
    address: "Plaça del Sol, 08012 Barcelona",
    latitude: "41.4060000",
    longitude: "2.1571000",
    localRating: "4.7",
    touristMentions: 75,
    localMentions: 1800,
    gemScore: 77,
    discoveryStatus: "hidden",
    daysUntilMainstream: 220,
    description: "The beating heart of the Gràcia neighbourhood — a square ringed with cafes, ice-cream bars, and locals on folding chairs who seem to have nowhere better to be. Best at aperitivo hour.",
    whyLocalsLoveIt: "This is the neighbourhood square every tourist city claims to have but rarely does. The terrace at Bar Canigó is the best seat in Barcelona.",
    bestFor: ["aperitivo", "people watching", "local atmosphere", "evening"],
    priceRange: "$",
    neighborhood: "gracia",
    imageUrl: "https://images.unsplash.com/photo-1559628233-c0b7f60bed7d?auto=format&fit=crop&w=800&q=80",
  },

  // ── BALI (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ───────────────────────
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Warung Babi Guling Ibu Oka",
    placeType: "restaurant",
    address: "Jl. Tegal Sari No.2, Ubud, Gianyar",
    latitude: "-8.5062000",
    longitude: "115.2629000",
    localRating: "4.8",
    touristMentions: 250,
    localMentions: 2000,
    gemScore: 81,
    discoveryStatus: "emerging",
    description: "The legendary whole-roasted suckling pig (babi guling) restaurant in Ubud. The crispy skin, spiced minced pork, and blood sausage set the gold standard. Sells out by 1pm.",
    whyLocalsLoveIt: "Every Balinese will tell you this is the best babi guling on the island. Arrive at 11am and order the full set.",
    bestFor: ["local cuisine", "lunch", "foodie", "cultural experience"],
    priceRange: "$",
    neighborhood: "ubud",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Shelter Coffee Canggu",
    placeType: "cafe",
    address: "Jl. Pantai Batu Mejan, Canggu, Badung",
    latitude: "-8.6476000",
    longitude: "115.1324000",
    localRating: "4.7",
    touristMentions: 180,
    localMentions: 1200,
    gemScore: 76,
    discoveryStatus: "emerging",
    description: "A multi-story open-air coffee and coworking space with paddy field views. Single-origin Flores and Toraja beans brewed meticulously by trained baristas with a calm, non-tourist atmosphere.",
    whyLocalsLoveIt: "The Bali expat community's office. The cold brew and avocado toast are executed better here than anywhere on the island.",
    bestFor: ["coffee", "coworking", "slow mornings", "digital nomad"],
    priceRange: "$",
    neighborhood: "canggu",
    imageUrl: "https://images.unsplash.com/photo-1517992130453-c2e6f0b1b5e4?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Pasar Badung Traditional Market",
    placeType: "food",
    address: "Jl. Sulawesi, Denpasar",
    latitude: "-8.6584000",
    longitude: "115.2171000",
    localRating: "4.6",
    touristMentions: 70,
    localMentions: 1800,
    gemScore: 74,
    discoveryStatus: "hidden",
    daysUntilMainstream: 200,
    description: "Bali's largest traditional market — four floors of exotic spices, temple offerings, tropical fruit, and satay vendors. The early morning is a festival of colour and smell that no hotel buffet can match.",
    whyLocalsLoveIt: "Balinese housewives shop here at 5am. The chaos is orderly once you understand it — and the tamarind iced drinks are incomparable.",
    bestFor: ["spice shopping", "local culture", "photography", "early morning"],
    priceRange: "$",
    neighborhood: "kuta",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Jatiluwih Rice Terraces Sunrise Walk",
    placeType: "scenic",
    address: "Jatiluwih, Tabanan Regency, Bali",
    latitude: "-8.3668000",
    longitude: "115.1290000",
    localRating: "4.9",
    touristMentions: 300,
    localMentions: 1500,
    gemScore: 88,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "A UNESCO-listed subak irrigation system 700m above sea level — the most photogenic rice terraces in Bali, far from the Tegallalang crowds. Sunrise turns the paddies a hundred shades of green.",
    whyLocalsLoveIt: "Tegallalang has become a selfie queue. Jatiluwih is what Bali's rice terraces should feel like — panoramic, working, and peaceful.",
    bestFor: ["photography", "hiking", "sunrise", "UNESCO site"],
    priceRange: "$",
    neighborhood: "ubud",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Pura Lempuyang Temple Gate",
    placeType: "viewpoint",
    address: "Pura Lempuyang, Karangasem Regency, Bali",
    latitude: "-8.3925000",
    longitude: "115.6316000",
    localRating: "4.9",
    touristMentions: 600,
    localMentions: 2000,
    gemScore: 85,
    discoveryStatus: "emerging",
    description: "The 'Gates of Heaven' split gate framing Mount Agung is Bali's most iconic composition. Arrive before 7am for an empty gate and natural light before the queue forms.",
    whyLocalsLoveIt: "The reflection pool photo is a mirror trick but the real gate with Agung framed behind it needs no tricks — just an early alarm.",
    bestFor: ["photography", "temple visit", "dawn", "iconic shot"],
    priceRange: "$",
    neighborhood: "sanur",
    imageUrl: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Komaneka at Bisma Ubud",
    placeType: "hotel",
    address: "Jl. Bisma, Ubud, Gianyar, Bali",
    latitude: "-8.5090000",
    longitude: "115.2573000",
    localRating: "4.9",
    touristMentions: 160,
    localMentions: 450,
    gemScore: 84,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A cliff-edge boutique resort in Ubud's ravine with infinity pool views over the jungle canopy and Wos River valley. Balinese pavilion architecture, art collection, and farm-to-table restaurant.",
    whyLocalsLoveIt: "The jungle breakfast with mist rising from the valley below is one of Bali's finest morning experiences. Worth the splurge.",
    bestFor: ["luxury stay", "honeymoon", "jungle views", "pool"],
    priceRange: "$$$$",
    neighborhood: "ubud",
    imageUrl: "https://images.unsplash.com/photo-1540541338537-ef5c5ee16535?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Tanah Lot Temple at Dusk",
    placeType: "attraction",
    address: "Tanah Lot, Tabanan Regency, Bali",
    latitude: "-8.6215000",
    longitude: "115.0867000",
    localRating: "4.8",
    touristMentions: 700,
    localMentions: 2500,
    gemScore: 80,
    discoveryStatus: "emerging",
    description: "A 16th-century Hindu sea temple perched on a rock stack in the Indian Ocean — dramatically lit at sunset when the tide rolls in. The surrounding sea snakes are considered sacred guardians.",
    whyLocalsLoveIt: "Come at low tide to walk to the temple base, then stay for the sunset on the clifftop. The crowd thins rapidly after the sun sets.",
    bestFor: ["temple visit", "sunset", "photography", "cultural experience"],
    priceRange: "$",
    neighborhood: "seminyak",
    imageUrl: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Bali",
    country: "Indonesia",
    placeName: "Semara Ratih Dance Performance",
    placeType: "activity",
    address: "Jl. Raya Kedewatan, Ubud, Gianyar",
    latitude: "-8.4921000",
    longitude: "115.2481000",
    localRating: "4.9",
    touristMentions: 130,
    localMentions: 900,
    gemScore: 82,
    discoveryStatus: "hidden",
    daysUntilMainstream: 250,
    description: "A small family-run performance space in the forest edge of Ubud presenting traditional Kecak, Legong, and Barong dances by master performers — none of the commercial staging of the palace shows.",
    whyLocalsLoveIt: "The performers here are the teachers that all the palace show dancers learned from. An intimate window into Balinese sacred performance.",
    bestFor: ["cultural performance", "traditional dance", "evening", "authentic experience"],
    priceRange: "$$",
    neighborhood: "ubud",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
  },

  // ── NEW YORK (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ───────────────────
  {
    city: "New York",
    country: "USA",
    placeName: "Di Fara Pizza Brooklyn",
    placeType: "restaurant",
    address: "1424 Avenue J, Brooklyn, NY 11230",
    latitude: "40.6249000",
    longitude: "-73.9617000",
    localRating: "4.9",
    touristMentions: 300,
    localMentions: 3500,
    gemScore: 89,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "Dom DeMarco's legendary Midwood pizzeria — one man making every pizza by hand since 1964. The square Sicilian slice with basil scissors fresh from a potted plant is New York's best pizza.",
    whyLocalsLoveIt: "Dom is in his 80s and still makes every pie. There is a wait, there is no ambiance, and it is worth every minute.",
    bestFor: ["pizza", "New York classics", "foodie", "lunch"],
    priceRange: "$",
    neighborhood: "williamsburg",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "Russ and Daughters Cafe",
    placeType: "cafe",
    address: "127 Orchard Street, New York, NY 10002",
    latitude: "40.7200000",
    longitude: "-73.9878000",
    localRating: "4.8",
    touristMentions: 250,
    localMentions: 2800,
    gemScore: 84,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "The sit-down cafe extension of the 1914 appetizing institution on Houston Street. The Super Heebster bagel — whitefish salad, horseradish cream cheese, wasabi flying fish roe — is New York's greatest bagel.",
    whyLocalsLoveIt: "Four generations of Jewish-American food culture in one room. The smoked salmon flight makes Sunday brunch a ceremony.",
    bestFor: ["brunch", "bagels", "NYC institution", "Jewish deli culture"],
    priceRange: "$$",
    neighborhood: "lower-east-side",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "Smorgasburg Williamsburg",
    placeType: "food",
    address: "East River State Park, Williamsburg, Brooklyn",
    latitude: "40.7131000",
    longitude: "-73.9631000",
    localRating: "4.7",
    touristMentions: 500,
    localMentions: 3000,
    gemScore: 80,
    discoveryStatus: "emerging",
    description: "A 100-vendor outdoor food market every Saturday (April–October) on the Williamsburg waterfront with Manhattan skyline views. Everything is original — no chains, no repeats, all made that day.",
    whyLocalsLoveIt: "The ramen burger was invented here. New vendors debut every season and Brooklynites track the lineup obsessively.",
    bestFor: ["street food", "Saturday morning", "food discovery", "Manhattan views"],
    priceRange: "$",
    neighborhood: "williamsburg",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "The Cloisters Fort Tryon Park",
    placeType: "attraction",
    address: "99 Margaret Corbin Drive, New York, NY 10040",
    latitude: "40.8647000",
    longitude: "-73.9317000",
    localRating: "4.9",
    touristMentions: 200,
    localMentions: 1800,
    gemScore: 86,
    discoveryStatus: "hidden",
    daysUntilMainstream: 400,
    description: "A medieval castle transplanted to upper Manhattan housing the Met's collection of medieval art and architecture. The Hudson River views from the gardens are as good as any in New York — and rarely crowded.",
    whyLocalsLoveIt: "The Unicorn Tapestries alone justify the trip. The gardens in May smell of medieval herbs. Most New Yorkers never make it here.",
    bestFor: ["museum", "art", "gardens", "Hudson views", "hidden NYC"],
    priceRange: "$",
    neighborhood: "washington-heights",
    imageUrl: "https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "High Line Chelsea at Sunset",
    placeType: "scenic",
    address: "High Line, Chelsea, New York, NY 10011",
    latitude: "40.7480000",
    longitude: "-74.0048000",
    localRating: "4.8",
    touristMentions: 800,
    localMentions: 3500,
    gemScore: 82,
    discoveryStatus: "emerging",
    description: "The 1.45-mile elevated park on a former freight rail line through Chelsea and Hell's Kitchen. Sunset from the 10th Avenue Square overlook — when the Hudson turns gold and the city lights come on — is one of NYC's best free views.",
    whyLocalsLoveIt: "Go on a weekday at 6pm. The tourist crowd has thinned and the Chelsea gallery-goers take over. The garden plantings in autumn are particularly beautiful.",
    bestFor: ["photography", "sunset", "urban gardens", "evening walk"],
    priceRange: "$",
    neighborhood: "chelsea",
    imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "DUMBO Brooklyn Bridge Viewpoint",
    placeType: "viewpoint",
    address: "Washington Street between Front and Water, DUMBO, Brooklyn",
    latitude: "40.7033000",
    longitude: "-73.9897000",
    localRating: "4.9",
    touristMentions: 700,
    localMentions: 2500,
    gemScore: 85,
    discoveryStatus: "emerging",
    description: "The Manhattan Bridge perfectly framed down Washington Street with the Brooklyn Bridge in the background — arguably the most photographed street perspective in New York. Best at blue hour when the bridge lights come on.",
    whyLocalsLoveIt: "It's a short walk from the F/A train at York Street. Go at 5:30am on a weekend and you'll have the shot without 50 people in frame.",
    bestFor: ["photography", "architecture", "golden hour", "iconic NYC shot"],
    priceRange: "$",
    neighborhood: "dumbo",
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "The Jane Hotel Greenwich Village",
    placeType: "hotel",
    address: "113 Jane Street, New York, NY 10014",
    latitude: "40.7357000",
    longitude: "-74.0094000",
    localRating: "4.6",
    touristMentions: 220,
    localMentions: 600,
    gemScore: 76,
    discoveryStatus: "hidden",
    daysUntilMainstream: 200,
    description: "A 1908 maritime hotel in the West Village — Titanic survivors stayed here. Cabin rooms are tiny but beautifully designed, and the Jane Ballroom hosts some of Manhattan's best underground parties.",
    whyLocalsLoveIt: "The ballroom and rooftop are fixtures of NYC's creative scene. The cabin rooms make you feel like you're bunking on a luxury steamship.",
    bestFor: ["boutique stay", "West Village location", "nightlife", "unique experience"],
    priceRange: "$$",
    neighborhood: "greenwich-village",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "New York",
    country: "USA",
    placeName: "Jazz at the Village Vanguard",
    placeType: "activity",
    address: "178 7th Avenue South, New York, NY 10014",
    latitude: "40.7338000",
    longitude: "-74.0007000",
    localRating: "4.9",
    touristMentions: 300,
    localMentions: 1800,
    gemScore: 88,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "The most important jazz club in the world — a wedge-shaped basement that has hosted Miles Davis, Coltrane, and Bill Evans since 1935. The Monday night Vanguard Jazz Orchestra residency has run for 50+ years.",
    whyLocalsLoveIt: "You are listening to jazz on the exact stage where the recordings you grew up with were made. Nothing in New York touches this for music history.",
    bestFor: ["jazz", "live music", "New York classics", "evening"],
    priceRange: "$$",
    neighborhood: "greenwich-village",
    imageUrl: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?auto=format&fit=crop&w=800&q=80",
  },

  // ── ROME (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ───────────────────────
  {
    city: "Rome",
    country: "Italy",
    placeName: "Da Enzo al 29 Trastevere",
    placeType: "restaurant",
    address: "Via dei Vascellari 29, 00153 Rome",
    latitude: "41.8876000",
    longitude: "12.4699000",
    localRating: "4.8",
    touristMentions: 200,
    localMentions: 2500,
    gemScore: 83,
    discoveryStatus: "hidden",
    daysUntilMainstream: 250,
    description: "A no-reservations Trastevere trattoria with checkered tablecloths, handwritten menus, and Roman classics done without compromise. The cacio e pepe and coda alla vaccinara are definitive versions.",
    whyLocalsLoveIt: "This is where Rome's restaurant industry eats on their nights off. Order the house wine, the seasonal artichokes, and whatever the specials board says.",
    bestFor: ["Roman cuisine", "pasta", "traditional trattoria", "dinner"],
    priceRange: "$$",
    neighborhood: "trastevere",
    imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Flavio al Velavevodetto Testaccio",
    placeType: "dining",
    address: "Via di Monte Testaccio 97, 00153 Rome",
    latitude: "41.8755000",
    longitude: "12.4773000",
    localRating: "4.7",
    touristMentions: 120,
    localMentions: 1800,
    gemScore: 80,
    discoveryStatus: "hidden",
    daysUntilMainstream: 280,
    description: "Built into the side of Monte Testaccio — literally a 35-metre hill of ancient Roman amphora sherds — this trattoria serves cucina romana povera at its finest. The rigatoni con pajata is a Roman rite of passage.",
    whyLocalsLoveIt: "The dining room has ancient ceramic sherds embedded in the wall. The menu is offal-forward, seasonal, and without concession to tourist tastes.",
    bestFor: ["offal cuisine", "Roman food culture", "historic setting", "dinner"],
    priceRange: "$$",
    neighborhood: "testaccio",
    imageUrl: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Mercato Testaccio Saturday Morning",
    placeType: "food",
    address: "Via Beniamino Franklin, 00153 Rome",
    latitude: "41.8760000",
    longitude: "12.4743000",
    localRating: "4.8",
    touristMentions: 100,
    localMentions: 2200,
    gemScore: 82,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "Rome's best covered market — a modern building replacing the beloved old market, packed with local producers selling Roman artichokes, porchetta, fresh pasta, and sheep ricotta so fresh it is still warm.",
    whyLocalsLoveIt: "The porchetta sandwiches here are the benchmark for all others. Go on Saturday when the seasonal produce sellers set up outside.",
    bestFor: ["food shopping", "local culture", "morning", "picnic"],
    priceRange: "$",
    neighborhood: "testaccio",
    imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Centrale Montemartini Museum",
    placeType: "attraction",
    address: "Via Ostiense 106, 00154 Rome",
    latitude: "41.8665000",
    longitude: "12.4802000",
    localRating: "4.9",
    touristMentions: 90,
    localMentions: 1200,
    gemScore: 87,
    discoveryStatus: "hidden",
    daysUntilMainstream: 400,
    description: "Ancient Roman sculptures displayed inside a 1912 electricity generating station — marble gods among industrial turbines and boiler rooms. One of Rome's most visually arresting and least-visited museums.",
    whyLocalsLoveIt: "The contrast of classical sculpture against industrial machinery is unlike anything in Rome's crowded museum circuit. Rarely has more than 50 visitors.",
    bestFor: ["museum", "art", "photography", "industrial design"],
    priceRange: "$",
    neighborhood: "ostiense",
    imageUrl: "https://images.unsplash.com/photo-1548574505-5e239809ee19?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Pigneto Aperitivo Strip",
    placeType: "activity",
    address: "Via del Pigneto, 00176 Rome",
    latitude: "41.8887000",
    longitude: "12.5204000",
    localRating: "4.7",
    touristMentions: 60,
    localMentions: 2000,
    gemScore: 78,
    discoveryStatus: "hidden",
    daysUntilMainstream: 280,
    description: "The pedestrian stretch of Via del Pigneto at aperitivo hour (6–9pm) is Rome's best kept secret — a street once populated by Pasolini's films now lined with indie bars offering €5 Negronis with generous snacks.",
    whyLocalsLoveIt: "Zero tourists, maximum Romans. This is where Rome's art school crowd, film industry workers, and neighbourhood old-timers converge at dusk.",
    bestFor: ["aperitivo", "nightlife", "local culture", "Negroni"],
    priceRange: "$",
    neighborhood: "pigneto",
    imageUrl: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Portrait Roma Hotel Prati",
    placeType: "hotel",
    address: "Via Bocca di Leone 23, 00187 Rome",
    latitude: "41.9055000",
    longitude: "12.4610000",
    localRating: "4.9",
    touristMentions: 180,
    localMentions: 400,
    gemScore: 83,
    discoveryStatus: "hidden",
    daysUntilMainstream: 350,
    description: "A 14-suite palazzo hotel on one of Rome's most elegant shopping streets, managed by the Ferragamo family. The rooftop with Castel Sant'Angelo and Vatican views is one of Rome's finest.",
    whyLocalsLoveIt: "The Ferragamo touch means every detail is considered — linens, breakfast, art. The bar terrace facing the Tiber at sunset is a local event.",
    bestFor: ["luxury stay", "couples", "rooftop views", "boutique"],
    priceRange: "$$$$",
    neighborhood: "prati",
    imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe2f5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Trastevere at Dawn Before the Tourists",
    placeType: "scenic",
    address: "Piazza di Santa Maria in Trastevere, 00153 Rome",
    latitude: "41.8895000",
    longitude: "12.4694000",
    localRating: "4.9",
    touristMentions: 500,
    localMentions: 2800,
    gemScore: 86,
    discoveryStatus: "hidden",
    daysUntilMainstream: 350,
    description: "The cobblestone neighbourhood of Trastevere at 6am is a different city — damp streets, cats, the golden mosaic of Santa Maria basilica glowing before the day's first Mass. Photography impossible to replicate by afternoon.",
    whyLocalsLoveIt: "Rome is a different city before 8am. The ochre light on the basilica mosaic in the deserted piazza is the city's finest secret visual.",
    bestFor: ["photography", "dawn", "architecture", "quiet Rome"],
    priceRange: "$",
    neighborhood: "trastevere",
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "Rome",
    country: "Italy",
    placeName: "Aventine Hill Orange Garden Keyhole",
    placeType: "viewpoint",
    address: "Piazza dei Cavalieri di Malta, 00153 Rome",
    latitude: "41.8817000",
    longitude: "12.4792000",
    localRating: "4.9",
    touristMentions: 250,
    localMentions: 1500,
    gemScore: 84,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A keyhole in the Knights of Malta priory gate on the Aventine Hill frames a perfect tunnel of cypress trees with St Peter's dome centred at the vanishing point. One of Rome's most secretive photo spots.",
    whyLocalsLoveIt: "The fact that you look through a keyhole at one of the world's most famous domes makes this absurdly and perfectly Roman. Queue is five minutes, not five hours.",
    bestFor: ["photography", "architecture", "hidden Rome", "iconic shot"],
    priceRange: "$",
    neighborhood: "trastevere",
    imageUrl: "https://images.unsplash.com/photo-1529154166925-574a0236a4f4?auto=format&fit=crop&w=800&q=80",
  },

  // ── LONDON (8 gems: 3 Eat · 2 Do · 1 Stay · 2 Photo) ─────────────────────
  {
    city: "London",
    country: "United Kingdom",
    placeName: "St John Bread and Wine Spitalfields",
    placeType: "restaurant",
    address: "94-96 Commercial Street, London E1 6LZ",
    latitude: "51.5178000",
    longitude: "-0.0758000",
    localRating: "4.8",
    touristMentions: 150,
    localMentions: 2000,
    gemScore: 82,
    discoveryStatus: "hidden",
    daysUntilMainstream: 240,
    description: "The east-end sibling of Fergus Henderson's nose-to-tail institution — same whole-animal ethos, simpler format. Bone marrow on toast, eccles cakes with Lancashire cheese, and a wine list of curious naturals.",
    whyLocalsLoveIt: "This is where London's chefs eat breakfast. The genius is in simplicity — perfect ingredients, zero technique fuss, honest bread.",
    bestFor: ["nose-to-tail", "brunch", "London classics", "foodie"],
    priceRange: "$$",
    neighborhood: "shoreditch",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Borough Market Thursday Lunch",
    placeType: "food",
    address: "8 Southwark Street, London SE1 1TL",
    latitude: "51.5054000",
    longitude: "-0.0910000",
    localRating: "4.7",
    touristMentions: 600,
    localMentions: 3000,
    gemScore: 79,
    discoveryStatus: "emerging",
    description: "London's oldest food market has weekend crowds, but Thursday lunch is the locals' time — fewer tourists, the same quality producers, and the Brindisa chorizo sandwich and Monmouth coffee still in full operation.",
    whyLocalsLoveIt: "The Gujarati vegetarian stall and the Roast pork roll from HG Walter are food industry secrets. Arrive at 12:30 when office workers thin out.",
    bestFor: ["street food", "lunch", "London food culture", "market"],
    priceRange: "$",
    neighborhood: "south-bank",
    imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Rochelle Canteen Shoreditch",
    placeType: "dining",
    address: "16 Playground Gardens, London E2 7FA",
    latitude: "51.5258000",
    longitude: "-0.0774000",
    localRating: "4.8",
    touristMentions: 80,
    localMentions: 1500,
    gemScore: 81,
    discoveryStatus: "hidden",
    daysUntilMainstream: 280,
    description: "A canteen inside a converted bike shed in a former Victorian school — the menu changes twice daily, British seasonal ingredients, and a garden terrace that feels like a secret. Ring the bell to enter.",
    whyLocalsLoveIt: "The lunch reservation list has a long wait because this is where London's creative industry spends its lunch hour. The daily menu handwriting is the best food journalism in the city.",
    bestFor: ["British seasonal", "creative industry crowd", "garden", "lunch"],
    priceRange: "$$",
    neighborhood: "shoreditch",
    imageUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Columbia Road Flower Market Sunday",
    placeType: "activity",
    address: "Columbia Road, London E2 7RG",
    latitude: "51.5298000",
    longitude: "-0.0758000",
    localRating: "4.9",
    touristMentions: 350,
    localMentions: 2800,
    gemScore: 85,
    discoveryStatus: "hidden",
    daysUntilMainstream: 365,
    description: "A Victorian street transforms every Sunday morning into London's most colourful flower and plant market — cockney barrow boys shouting prices while East End galleries and brunch spots open their doors alongside.",
    whyLocalsLoveIt: "The 8am plant deals before tourists arrive are the best. The sellers' patter is performance art. The Dutch House cafe does the best fry-up in Shoreditch.",
    bestFor: ["Sunday morning", "photography", "plants", "local culture"],
    priceRange: "$",
    neighborhood: "shoreditch",
    imageUrl: "https://images.unsplash.com/photo-1490750967868-88df5691cc90?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Tate Modern Switch House Rooftop",
    placeType: "viewpoint",
    address: "Bankside, London SE1 9TG",
    latitude: "51.5076000",
    longitude: "-0.0994000",
    localRating: "4.8",
    touristMentions: 300,
    localMentions: 1800,
    gemScore: 83,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "The 10th-floor viewing terrace on the Blavatnik Building addition to Tate Modern gives a 360-degree Thames panorama — St Paul's, Tower Bridge, the City skyline — for free, no ticket required.",
    whyLocalsLoveIt: "Better views than the Shard without the £33 ticket. Take the lift to level 10 and walk out. Free, open until 10pm on Fridays and Saturdays.",
    bestFor: ["panoramic views", "photography", "free", "Thames vista"],
    priceRange: "$",
    neighborhood: "south-bank",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "The Zetter Townhouse Clerkenwell",
    placeType: "hotel",
    address: "49-50 St John's Square, London EC1V 4JJ",
    latitude: "51.5225000",
    longitude: "-0.1026000",
    localRating: "4.8",
    touristMentions: 170,
    localMentions: 450,
    gemScore: 80,
    discoveryStatus: "hidden",
    daysUntilMainstream: 300,
    description: "A 13-room boutique hotel in a Georgian townhouse around the Clerkenwell square — the cocktail lounge is London's most eccentric, with a taxidermy owl, mismatched antiques, and signature cocktails named after fictional aunts.",
    whyLocalsLoveIt: "The Zetter cocktail bar is a destination in itself. The rooms feel like staying in a very well-curated eccentric relative's home.",
    bestFor: ["boutique stay", "cocktails", "Clerkenwell location", "couples"],
    priceRange: "$$$",
    neighborhood: "shoreditch",
    imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe2f5?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Portobello Road Notting Hill at Dawn",
    placeType: "scenic",
    address: "Portobello Road, London W11",
    latitude: "51.5144000",
    longitude: "-0.2047000",
    localRating: "4.8",
    touristMentions: 600,
    localMentions: 2200,
    gemScore: 82,
    discoveryStatus: "emerging",
    description: "The pastel-painted townhouses of Portobello Road photographed at 7am on a Friday — before the antique stalls set up and the crowds arrive — are the most recognisable street image in London.",
    whyLocalsLoveIt: "The colours are best in morning light, the street is empty, and you can see the architecture clearly. The antique dealers arriving to set up make a great candid.",
    bestFor: ["photography", "architecture", "Notting Hill", "dawn"],
    priceRange: "$",
    neighborhood: "notting-hill",
    imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=800&q=80",
  },
  {
    city: "London",
    country: "United Kingdom",
    placeName: "Leake Street Graffiti Tunnel",
    placeType: "attraction",
    address: "Leake Street, Lambeth, London SE1",
    latitude: "51.5012000",
    longitude: "-0.1119000",
    localRating: "4.7",
    touristMentions: 180,
    localMentions: 1200,
    gemScore: 76,
    discoveryStatus: "hidden",
    daysUntilMainstream: 200,
    description: "A 300-metre tunnel under Waterloo Station where legal graffiti transforms the walls continuously — Banksy launched the tunnel in 2008. New works appear overnight and the entire canvas changes every few weeks.",
    whyLocalsLoveIt: "Come twice and you'll never see the same artwork. Skaters, urban artists, and photographers coexist in one of London's genuinely underground spaces.",
    bestFor: ["street art", "photography", "urban culture", "free"],
    priceRange: "$",
    neighborhood: "south-bank",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
  },

  // ── VIETNAM (ruling 117 — decision-maker: "seed up-and-coming markets like Vietnam") ──
  // Every place below is REAL and verifiable; coordinates are city-accurate approximations.
  // No Stay entries: unlike the launch cities we have no vetted hidden stays to name, and a
  // guessed hotel would violate §13 — the category is simply absent rather than fabricated.
  // imageUrl is omitted throughout (no verified photo rights) — the feed renders imageless
  // cards honestly.

  // ── HANOI (3 Eat · 3 Do · 2 Photo) ──
  {
    city: "Hanoi", country: "Vietnam",
    placeName: "Cafe Giang", placeType: "cafe",
    address: "39 Nguyen Huu Huan, Hoan Kiem, Hanoi",
    latitude: "21.0339000", longitude: "105.8527000",
    localRating: "4.6", touristMentions: 480, localMentions: 1200, gemScore: 74,
    discoveryStatus: "emerging", daysUntilMainstream: 90,
    description: "The birthplace of Hanoi egg coffee (ca phe trung), run by the founding family since 1946 — whipped egg yolk over dark robusta, served up a narrow staircase off the Old Quarter.",
    whyLocalsLoveIt: "The original recipe, unchanged; locals take the upstairs corner seats tourists walk past.",
    bestFor: ["coffee", "rainy mornings", "solo travel"],
    priceRange: "$", neighborhood: "hoan-kiem",
  },
  {
    city: "Hanoi", country: "Vietnam",
    placeName: "Banh Cuon Gia Truyen Thanh Van", placeType: "restaurant",
    address: "14 Hang Ga, Hoan Kiem, Hanoi",
    latitude: "21.0353000", longitude: "105.8461000",
    localRating: "4.5", touristMentions: 90, localMentions: 760, gemScore: 81,
    discoveryStatus: "hidden", daysUntilMainstream: 240,
    description: "Steamed rice-sheet rolls (banh cuon) made to order on cloth steamers at the front counter, filled with minced pork and wood-ear mushroom, eaten at dawn with fried shallots.",
    whyLocalsLoveIt: "Breakfast counter theatre — the steamer never stops, and it is gone by late morning.",
    bestFor: ["breakfast", "street food", "early risers"],
    priceRange: "$", neighborhood: "hoan-kiem",
  },
  {
    city: "Hanoi", country: "Vietnam",
    placeName: "Tong Duy Tan food street", placeType: "food street",
    address: "Tong Duy Tan, Hoan Kiem, Hanoi",
    latitude: "21.0296000", longitude: "105.8442000",
    localRating: "4.3", touristMentions: 150, localMentions: 900, gemScore: 72,
    discoveryStatus: "emerging", daysUntilMainstream: 150,
    description: "Hanoi's designated 24-hour eating street — ga tan (medicinal braised chicken), pho cuon and late-night hotpot, at its best after 10pm when the kitchens cook for locals.",
    whyLocalsLoveIt: "The only street where everything is still open at 2am, and the ga tan broth is winter medicine.",
    bestFor: ["late night", "street food", "groups"],
    priceRange: "$", neighborhood: "hoan-kiem",
  },
  {
    city: "Hanoi", country: "Vietnam",
    placeName: "Quang Ba flower market at dawn", placeType: "market",
    address: "Au Co, Tay Ho, Hanoi",
    latitude: "21.0705000", longitude: "105.8280000",
    localRating: "4.7", touristMentions: 60, localMentions: 540, gemScore: 86,
    discoveryStatus: "hidden", daysUntilMainstream: 300,
    description: "Hanoi's wholesale flower market, busiest between 3am and 6am — motorbikes stacked with lotus, lilies and chrysanthemums under sodium lights on the West Lake dyke road.",
    whyLocalsLoveIt: "Where every flower shop in the city buys before sunrise; go once and you never forget the smell.",
    bestFor: ["sunrise", "photography", "off the path"],
    priceRange: "$", neighborhood: "tay-ho",
  },
  {
    city: "Hanoi", country: "Vietnam",
    placeName: "Phung Hung mural street", placeType: "attraction",
    address: "Phung Hung, Hoan Kiem, Hanoi",
    latitude: "21.0362000", longitude: "105.8440000",
    localRating: "4.2", touristMentions: 200, localMentions: 480, gemScore: 68,
    discoveryStatus: "emerging", daysUntilMainstream: 120,
    description: "The railway-viaduct arches along Phung Hung painted as a public gallery of old-Hanoi scenes — tram cars, street vendors, Tet flower markets — beside the real Long Bien rail line.",
    whyLocalsLoveIt: "Weekend ao dai photo shoots and grandparents pointing at the Hanoi they grew up in.",
    bestFor: ["walking", "photography", "families"],
    priceRange: "$", neighborhood: "hoan-kiem",
  },
  {
    city: "Hanoi", country: "Vietnam",
    placeName: "Long Bien Bridge sunrise walk", placeType: "viewpoint",
    address: "Long Bien Bridge, Hanoi",
    latitude: "21.0435000", longitude: "105.8590000",
    localRating: "4.6", touristMentions: 260, localMentions: 700, gemScore: 76,
    discoveryStatus: "emerging", daysUntilMainstream: 180,
    description: "The 1902 Eiffel-era cantilever bridge across the Red River — walk the pedestrian lane at first light as trains rattle past and farmers carry produce in from the banana groves.",
    whyLocalsLoveIt: "The bridge survived the war and the city grew around it; sunrise here is Hanoi's quietest hour.",
    bestFor: ["sunrise", "photography", "history"],
    priceRange: "$", neighborhood: "long-bien",
  },
  {
    city: "Hanoi", country: "Vietnam",
    placeName: "Red River banana island rock field (Bai da song Hong)", placeType: "photo spot",
    address: "Ngoc Thuy banks, Red River, Hanoi",
    latitude: "21.0600000", longitude: "105.8300000",
    localRating: "4.1", touristMentions: 30, localMentions: 390, gemScore: 79,
    discoveryStatus: "hidden", daysUntilMainstream: 240,
    description: "A stretch of river flats and gardens below the dyke where Hanoians come for engagement photos among reeds, banana palms and the river light — ten minutes from the Old Quarter, a world away.",
    whyLocalsLoveIt: "Golden-hour picnics with the city skyline behind the reeds.",
    bestFor: ["golden hour", "photography", "couples"],
    priceRange: "$", neighborhood: "tay-ho",
  },
  {
    city: "Hanoi", country: "Vietnam",
    placeName: "Hanoi Ceramic Mosaic Mural road", placeType: "attraction",
    address: "Au Co - Nghi Tam dyke road, Hanoi",
    latitude: "21.0620000", longitude: "105.8360000",
    localRating: "4.0", touristMentions: 110, localMentions: 350, gemScore: 66,
    discoveryStatus: "emerging", daysUntilMainstream: 200,
    description: "A four-kilometre ceramic mosaic along the Red River dyke — one of the world's largest — telling Vietnam's history from Dong Son drums to modern Hanoi, best seen slowly by bicycle.",
    whyLocalsLoveIt: "Made for the city's 1000th birthday; every neighborhood contributed a panel.",
    bestFor: ["cycling", "history", "photography"],
    priceRange: "$", neighborhood: "tay-ho",
  },

  // ── DA NANG (3 Eat · 3 Do · 2 Photo) ──
  {
    city: "Da Nang", country: "Vietnam",
    placeName: "Banh Xeo Ba Duong", placeType: "restaurant",
    address: "K280/23 Hoang Dieu, Hai Chau, Da Nang",
    latitude: "16.0590000", longitude: "108.2170000",
    localRating: "4.6", touristMentions: 140, localMentions: 980, gemScore: 80,
    discoveryStatus: "hidden", daysUntilMainstream: 200,
    description: "Down a lane off Hoang Dieu, the city's benchmark banh xeo — turmeric crepes fried to order, rolled in rice paper with herbs and dipped in the house peanut-liver sauce.",
    whyLocalsLoveIt: "The alley address filters out anyone not serious; the nem lui skewers are the move.",
    bestFor: ["dinner", "street food", "groups"],
    priceRange: "$", neighborhood: "hai-chau",
  },
  {
    city: "Da Nang", country: "Vietnam",
    placeName: "Mi Quang 1A", placeType: "restaurant",
    address: "1 Hai Phong, Hai Chau, Da Nang",
    latitude: "16.0740000", longitude: "108.2210000",
    localRating: "4.4", touristMentions: 180, localMentions: 850, gemScore: 71,
    discoveryStatus: "emerging", daysUntilMainstream: 150,
    description: "The classic address for the region's signature dish — mi quang turmeric noodles with shrimp, pork and rice crackers, served since the 1970s and still packed with office workers at lunch.",
    whyLocalsLoveIt: "This is the bowl Da Nang people bring visiting relatives to first.",
    bestFor: ["lunch", "local classics", "first-timers"],
    priceRange: "$", neighborhood: "hai-chau",
  },
  {
    city: "Da Nang", country: "Vietnam",
    placeName: "Con Market street-food lane", placeType: "market",
    address: "Cho Con, 269 Ong Ich Khiem, Hai Chau, Da Nang",
    latitude: "16.0678000", longitude: "108.2140000",
    localRating: "4.3", touristMentions: 220, localMentions: 1100, gemScore: 69,
    discoveryStatus: "emerging", daysUntilMainstream: 120,
    description: "The food lanes inside Da Nang's oldest market — banh beo, che sweet soups, quang-style noodles and grilled rice paper, eaten on plastic stools among the fabric stalls.",
    whyLocalsLoveIt: "A dozen dishes in one sitting for the price of one beach-road main.",
    bestFor: ["grazing", "budget", "rainy days"],
    priceRange: "$", neighborhood: "hai-chau",
  },
  {
    city: "Da Nang", country: "Vietnam",
    placeName: "Nam O fishing village", placeType: "activity",
    address: "Nam O, Lien Chieu, Da Nang",
    latitude: "16.1130000", longitude: "108.1290000",
    localRating: "4.5", touristMentions: 40, localMentions: 420, gemScore: 84,
    discoveryStatus: "hidden", daysUntilMainstream: 300,
    description: "The village that invented Nam O fish sauce, at the foot of the Hai Van pass — dawn fish auctions on the beach, a coral reef offshore in the dry season, and mam nem sold from family courtyards.",
    whyLocalsLoveIt: "The reef at Nam O rocks turns emerald in April–August and most of the city has still never been.",
    bestFor: ["sunrise", "culture", "off the path"],
    priceRange: "$", neighborhood: "lien-chieu",
  },
  {
    city: "Da Nang", country: "Vietnam",
    placeName: "Son Tra peninsula coast road", placeType: "activity",
    address: "Hoang Sa road, Son Tra, Da Nang",
    latitude: "16.1000000", longitude: "108.2780000",
    localRating: "4.7", touristMentions: 380, localMentions: 760, gemScore: 73,
    discoveryStatus: "emerging", daysUntilMainstream: 150,
    description: "The jungle headland locals call Monkey Mountain — a coast road of empty coves past the Linh Ung pagoda, home to the endangered red-shanked douc langur; go by motorbike before 8am.",
    whyLocalsLoveIt: "Ten minutes from the beach strip and you can have a cove to yourself on a weekday.",
    bestFor: ["motorbike", "nature", "swimming"],
    priceRange: "$", neighborhood: "son-tra",
  },
  {
    city: "Da Nang", country: "Vietnam",
    placeName: "Man Thai beach basket boats at dawn", placeType: "photo spot",
    address: "Man Thai beach, Son Tra, Da Nang",
    latitude: "16.0830000", longitude: "108.2520000",
    localRating: "4.4", touristMentions: 50, localMentions: 380, gemScore: 82,
    discoveryStatus: "hidden", daysUntilMainstream: 240,
    description: "The fishing end of the city beach — round thung chai basket boats coming in at first light, nets sorted on the sand, and the day's catch sold straight off the boats.",
    whyLocalsLoveIt: "The working beach the resort strip forgot; the light at 5:30am is the photograph.",
    bestFor: ["sunrise", "photography", "culture"],
    priceRange: "$", neighborhood: "son-tra",
  },
  {
    city: "Da Nang", country: "Vietnam",
    placeName: "Hai Van Pass north viewpoint", placeType: "viewpoint",
    address: "Hai Van Pass, QL1A, Da Nang",
    latitude: "16.2000000", longitude: "108.1130000",
    localRating: "4.8", touristMentions: 900, localMentions: 600, gemScore: 65,
    discoveryStatus: "trending", daysUntilMainstream: 60,
    description: "The 'ocean cloud pass' between Da Nang and Hue — brick war-era gate towers at the summit, and a hairpin coast view that earns the motorbike ride up.",
    whyLocalsLoveIt: "Da Nang side up at dawn beats the tour-bus hour by a full morning.",
    bestFor: ["motorbike", "views", "day trips"],
    priceRange: "$", neighborhood: "lien-chieu",
  },
  {
    city: "Da Nang", country: "Vietnam",
    placeName: "Thanh Khe fish sauce lane breakfast", placeType: "food",
    address: "Nguyen Tat Thanh coastal road, Thanh Khe, Da Nang",
    latitude: "16.0770000", longitude: "108.1900000",
    localRating: "4.2", touristMentions: 20, localMentions: 310, gemScore: 78,
    discoveryStatus: "hidden", daysUntilMainstream: 300,
    description: "The bay-side stretch where fishing families sell bun cha ca (fish-cake noodle soup) from front rooms facing the water — the fish came off the boats an hour earlier.",
    whyLocalsLoveIt: "The broth is judged by fishermen, which keeps everyone honest.",
    bestFor: ["breakfast", "seafood", "budget"],
    priceRange: "$", neighborhood: "thanh-khe",
  },

  // ── HOI AN (3 Eat · 3 Do · 2 Photo) ──
  {
    city: "Hoi An", country: "Vietnam",
    placeName: "Banh Mi Madam Khanh", placeType: "restaurant",
    address: "115 Tran Cao Van, Hoi An",
    latitude: "15.8830000", longitude: "108.3250000",
    localRating: "4.5", touristMentions: 520, localMentions: 640, gemScore: 67,
    discoveryStatus: "trending", daysUntilMainstream: 60,
    description: "'The Banh Mi Queen' — a family stall a block outside the tourist core, layering pate, herbs, papaya and five sauces into the town's benchmark sandwich since the 1980s.",
    whyLocalsLoveIt: "Still assembled by the founding family, still under two dollars.",
    bestFor: ["lunch", "street food", "budget"],
    priceRange: "$", neighborhood: "cam-pho",
  },
  {
    city: "Hoi An", country: "Vietnam",
    placeName: "Cao Lau Thanh", placeType: "restaurant",
    address: "26 Thai Phien, Hoi An",
    latitude: "15.8790000", longitude: "108.3300000",
    localRating: "4.4", touristMentions: 90, localMentions: 520, gemScore: 77,
    discoveryStatus: "hidden", daysUntilMainstream: 180,
    description: "A no-sign family kitchen for Hoi An's own noodle — chewy cao lau made the old way, with char siu pork, greens and crisp croutons, in a dish that exists nowhere else in Vietnam.",
    whyLocalsLoveIt: "Legend says real cao lau needs water from the town's ancient Ba Le well; this family still believes it.",
    bestFor: ["lunch", "local classics", "food history"],
    priceRange: "$", neighborhood: "minh-an",
  },
  {
    city: "Hoi An", country: "Vietnam",
    placeName: "Reaching Out Tea House", placeType: "cafe",
    address: "131 Tran Phu, Hoi An",
    latitude: "15.8770000", longitude: "108.3270000",
    localRating: "4.8", touristMentions: 610, localMentions: 340, gemScore: 70,
    discoveryStatus: "emerging", daysUntilMainstream: 90,
    description: "A silent teahouse in a 200-year-old shophouse, staffed by deaf and speech-impaired hosts — orders pass on wooden message blocks, and the old town's noise stays outside.",
    whyLocalsLoveIt: "A social enterprise the town is proud of, and the quietest room on the busiest street.",
    bestFor: ["tea", "quiet", "meaningful travel"],
    priceRange: "$$", neighborhood: "minh-an",
  },
  {
    city: "Hoi An", country: "Vietnam",
    placeName: "Tra Que vegetable village", placeType: "activity",
    address: "Tra Que, Cam Ha, Hoi An",
    latitude: "15.8990000", longitude: "108.3400000",
    localRating: "4.5", touristMentions: 340, localMentions: 460, gemScore: 68,
    discoveryStatus: "emerging", daysUntilMainstream: 120,
    description: "The herb-garden village between the old town and An Bang beach — seaweed-composted beds worked by hand, reachable by bicycle through the rice paddies in fifteen minutes.",
    whyLocalsLoveIt: "The mint and rau ram in every good Hoi An dish comes from these exact beds.",
    bestFor: ["cycling", "food origins", "families"],
    priceRange: "$", neighborhood: "cam-ha",
  },
  {
    city: "Hoi An", country: "Vietnam",
    placeName: "Cam Thanh coconut forest by basket boat", placeType: "activity",
    address: "Cam Thanh, Hoi An",
    latitude: "15.8660000", longitude: "108.3720000",
    localRating: "4.2", touristMentions: 700, localMentions: 380, gemScore: 62,
    discoveryStatus: "trending", daysUntilMainstream: 45,
    description: "Seven hectares of water-coconut palms in the Thu Bon estuary, paddled in round basket boats — go early with a village rower rather than midday with the karaoke flotillas.",
    whyLocalsLoveIt: "The palms hid resistance fighters in the war; the grandmothers who paddle you remember.",
    bestFor: ["morning", "families", "slow travel"],
    priceRange: "$$", neighborhood: "cam-thanh",
  },
  {
    city: "Hoi An", country: "Vietnam",
    placeName: "Hoi An riverfront fish market at dawn", placeType: "market",
    address: "Bach Dang, Hoi An",
    latitude: "15.8770000", longitude: "108.3310000",
    localRating: "4.6", touristMentions: 80, localMentions: 540, gemScore: 83,
    discoveryStatus: "hidden", daysUntilMainstream: 240,
    description: "Before the lanterns switch on for tourists, the same riverfront hosts the town's real economy — boats unloading at 5am, headlamp auctions, and the day's cao lau pork changing hands.",
    whyLocalsLoveIt: "The only hour when the ancient town belongs to the people who live in it.",
    bestFor: ["sunrise", "photography", "culture"],
    priceRange: "$", neighborhood: "minh-an",
  },
  {
    city: "Hoi An", country: "Vietnam",
    placeName: "An Bang beach north end", placeType: "photo spot",
    address: "An Bang, Cam An, Hoi An",
    latitude: "15.9050000", longitude: "108.3390000",
    localRating: "4.4", touristMentions: 450, localMentions: 520, gemScore: 66,
    discoveryStatus: "emerging", daysUntilMainstream: 90,
    description: "Walk ten minutes north of the main beach entrance and the sunbed rows give way to fishing-family shacks, basket boats and an empty horizon toward the Cham Islands.",
    whyLocalsLoveIt: "Same beach, none of the crowd — and the seafood shacks charge village prices.",
    bestFor: ["swimming", "seafood", "sunset"],
    priceRange: "$", neighborhood: "cam-an",
  },
  {
    city: "Hoi An", country: "Vietnam",
    placeName: "Tan Thanh beach weekend flea market", placeType: "market",
    address: "Tan Thanh beach, Cam An, Hoi An",
    latitude: "15.9010000", longitude: "108.3360000",
    localRating: "4.1", touristMentions: 60, localMentions: 290, gemScore: 75,
    discoveryStatus: "hidden", daysUntilMainstream: 180,
    description: "A Saturday-morning beachfront market of local makers — ceramics, secondhand ao dai, natural dyes and coffee carts on the sand, started by the neighborhood after the pandemic.",
    whyLocalsLoveIt: "Hoi An's young creative scene in one place, with a swim after.",
    bestFor: ["weekends", "shopping", "coffee"],
    priceRange: "$$", neighborhood: "cam-an",
  },

  // ── HO CHI MINH CITY (3 Eat · 3 Do · 2 Photo) ──
  {
    city: "Ho Chi Minh City", country: "Vietnam",
    placeName: "The Lunch Lady (Nguyen Thi Thanh)", placeType: "restaurant",
    address: "23 Hoang Sa, Da Kao, District 1, Ho Chi Minh City",
    latitude: "10.7920000", longitude: "106.6980000",
    localRating: "4.5", touristMentions: 640, localMentions: 720, gemScore: 64,
    discoveryStatus: "trending", daysUntilMainstream: 60,
    description: "A canal-side stall with a different noodle soup every day of the week — bun bo Hue on Monday, bun mam on Friday — made famous abroad but still cooking for the neighborhood first.",
    whyLocalsLoveIt: "You eat whatever day it is; regulars plan their week around Thursday's bun thai.",
    bestFor: ["lunch", "street food", "adventurous eaters"],
    priceRange: "$", neighborhood: "da-kao",
  },
  {
    city: "Ho Chi Minh City", country: "Vietnam",
    placeName: "Cheo Leo Cafe", placeType: "cafe",
    address: "36/12 Nguyen Thien Thuat, District 3, Ho Chi Minh City",
    latitude: "10.7680000", longitude: "106.6810000",
    localRating: "4.7", touristMentions: 70, localMentions: 610, gemScore: 85,
    discoveryStatus: "hidden", daysUntilMainstream: 240,
    description: "Saigon's oldest cafe (1938), third-generation, still brewing ca phe vot through cloth 'socks' in clay pots over charcoal — deep in an alley the width of a motorbike.",
    whyLocalsLoveIt: "The last of the true vot houses; the owner will show you the 80-year-old roasting pan.",
    bestFor: ["coffee", "history", "mornings"],
    priceRange: "$", neighborhood: "district-3",
  },
  {
    city: "Ho Chi Minh City", country: "Vietnam",
    placeName: "Thanh Da island evening food strip", placeType: "food street",
    address: "Thanh Da, Binh Thanh, Ho Chi Minh City",
    latitude: "10.8280000", longitude: "106.7190000",
    localRating: "4.2", touristMentions: 30, localMentions: 450, gemScore: 80,
    discoveryStatus: "hidden", daysUntilMainstream: 300,
    description: "A river-ringed peninsula ten minutes from the towers where Saigon goes for breeze and snails — oc restaurants, grilled rice-field rat for the brave, and hammock cafes on the water.",
    whyLocalsLoveIt: "The city's cheapest waterfront table, and the skyline view belongs to the locals.",
    bestFor: ["evening", "seafood", "off the path"],
    priceRange: "$", neighborhood: "binh-thanh",
  },
  {
    city: "Ho Chi Minh City", country: "Vietnam",
    placeName: "Hao Si Phuong heritage alley", placeType: "attraction",
    address: "206 Tran Hung Dao B, District 5, Ho Chi Minh City",
    latitude: "10.7520000", longitude: "106.6620000",
    localRating: "4.3", touristMentions: 120, localMentions: 380, gemScore: 74,
    discoveryStatus: "emerging", daysUntilMainstream: 120,
    description: "A century-old double-decker Chinese tenement alley in Cho Lon — pastel balconies, shrine doors and shared staircases that have housed the same families for four generations.",
    whyLocalsLoveIt: "Cho Lon's living room; residents tolerate photographers who say hello first.",
    bestFor: ["photography", "history", "walking"],
    priceRange: "$", neighborhood: "cho-lon",
  },
  {
    city: "Ho Chi Minh City", country: "Vietnam",
    placeName: "Binh Tay Market (Cho Lon)", placeType: "market",
    address: "57A Thap Muoi, District 6, Ho Chi Minh City",
    latitude: "10.7500000", longitude: "106.6510000",
    localRating: "4.2", touristMentions: 380, localMentions: 820, gemScore: 63,
    discoveryStatus: "emerging", daysUntilMainstream: 90,
    description: "The 1920s clock-tower market at the heart of Chinatown — wholesale spice pyramids, dried seafood, and a courtyard shrine to the founder, with a food floor tourists rarely find.",
    whyLocalsLoveIt: "Ben Thanh sells to visitors; Binh Tay sells to the city.",
    bestFor: ["markets", "spices", "breakfast"],
    priceRange: "$", neighborhood: "cho-lon",
  },
  {
    city: "Ho Chi Minh City", country: "Vietnam",
    placeName: "Giac Lam Pagoda", placeType: "temple",
    address: "565 Lac Long Quan, Tan Binh, Ho Chi Minh City",
    latitude: "10.7920000", longitude: "106.6500000",
    localRating: "4.6", touristMentions: 90, localMentions: 470, gemScore: 78,
    discoveryStatus: "hidden", daysUntilMainstream: 240,
    description: "The city's oldest pagoda (1744) — a courtyard of frangipani and bodhi trees, 98 carved hardwood pillars and gilded arhats, with none of the downtown temple crowds.",
    whyLocalsLoveIt: "Where Saigon families actually come to pray on the 1st and 15th of the lunar month.",
    bestFor: ["quiet", "architecture", "culture"],
    priceRange: "$", neighborhood: "tan-binh",
  },
  {
    city: "Ho Chi Minh City", country: "Vietnam",
    placeName: "14 Ton That Dam old apartment cafes", placeType: "photo spot",
    address: "14 Ton That Dam, District 1, Ho Chi Minh City",
    latitude: "10.7710000", longitude: "106.7040000",
    localRating: "4.3", touristMentions: 260, localMentions: 520, gemScore: 69,
    discoveryStatus: "emerging", daysUntilMainstream: 90,
    description: "A crumbling 1960s apartment block colonized floor-by-floor by independent cafes, vintage shops and studios — climb the bare stairwell and pick a balcony over the old bank district.",
    whyLocalsLoveIt: "Each floor is someone's twenty-something dream; the stairwell graffiti is part of the lease.",
    bestFor: ["coffee", "photography", "rainy afternoons"],
    priceRange: "$$", neighborhood: "district-1",
  },
  {
    city: "Ho Chi Minh City", country: "Vietnam",
    placeName: "Saigon riverside at Thu Thiem crossing", placeType: "viewpoint",
    address: "Thu Thiem riverside park, Thu Duc, Ho Chi Minh City",
    latitude: "10.7830000", longitude: "106.7220000",
    localRating: "4.4", touristMentions: 150, localMentions: 680, gemScore: 71,
    discoveryStatus: "emerging", daysUntilMainstream: 120,
    description: "The grass bank across the river from District 1 — the full skyline from Bitexco to Landmark 81 at dusk, food carts, kite flyers and the cross-river breeze the old city lost.",
    whyLocalsLoveIt: "Saigon's free front-row seat to its own skyline; sunset picnics without a rooftop-bar bill.",
    bestFor: ["sunset", "picnics", "skyline photos"],
    priceRange: "$", neighborhood: "thu-thiem",
  },

];

export async function seedPopularCitiesContent(): Promise<{ gems: number }> {
  let gemsCreated = 0;

  // ── Hidden Gems ──────────────────────────────────────────────────────────
  for (const gem of HIDDEN_GEMS) {
    const existing = await db
      .select({ id: travelPulseHiddenGems.id })
      .from(travelPulseHiddenGems)
      .where(
        and(
          eq(travelPulseHiddenGems.city, gem.city),
          eq(travelPulseHiddenGems.placeName, gem.placeName),
        ),
      )
      .limit(1);

    if (existing.length > 0) {
      // Patch imageUrl on already-seeded rows that are missing a photo
      if (gem.imageUrl) {
        await db
          .update(travelPulseHiddenGems)
          .set({ imageUrl: gem.imageUrl })
          .where(
            and(
              eq(travelPulseHiddenGems.id, existing[0].id),
              or(
                isNull(travelPulseHiddenGems.imageUrl),
                eq(travelPulseHiddenGems.imageUrl, ""),
              ),
            ),
          );
      }
      continue;
    }

    await db.insert(travelPulseHiddenGems).values({
      city: gem.city,
      country: gem.country,
      placeName: gem.placeName,
      placeType: gem.placeType,
      address: gem.address,
      latitude: gem.latitude,
      longitude: gem.longitude,
      localRating: gem.localRating,
      touristMentions: gem.touristMentions,
      localMentions: gem.localMentions,
      gemScore: gem.gemScore,
      discoveryStatus: gem.discoveryStatus,
      daysUntilMainstream: gem.daysUntilMainstream,
      description: gem.description,
      whyLocalsLoveIt: gem.whyLocalsLoveIt,
      bestFor: gem.bestFor,
      priceRange: gem.priceRange,
      neighborhood: gem.neighborhood,
      imageUrl: gem.imageUrl,
      aiGenerated: false,
    });
    gemsCreated++;
  }

  return { gems: gemsCreated };
}

const isMainModule = /popular-cities-content\.seed\.(?:ts|js|mjs)$/.test(process.argv[1] ?? "");
if (isMainModule) {
  seedPopularCitiesContent()
    .then(({ gems }) => {
      console.log(`[popular-cities-content] Seed complete: ${gems} gems inserted.`);
      process.exit(0);
    })
    .catch((err) => {
      console.error("[popular-cities-content] Seed failed:", err);
      process.exit(1);
    });
}
