# Generated by Django 5.2.3 on 2025-08-28 16:17

import django.core.files.storage
from django.db import migrations, models
import authentication.models

class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allservice',
            name='service_file',
            field=models.FileField(blank=True, null=True, storage=authentication.models.UUIDTimeStampS3Storage(), upload_to='serviceprovider/services/'),
        ),
    ]
