# Generated by Django 5.2.3 on 2025-09-05 16:27

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviderapp', '0002_alter_allservice_service_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allservice',
            name='service_file',
            field=models.FileField(blank=True, null=True, storage=authentication.models.UUIDTimeStampedFileSystemStorage(), upload_to='serviceprovider/services/'),
        ),
    ]
