# Generated by Django 5.2.3 on 2025-07-29 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_itinerary', '0003_affiliateplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripSelectedFlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('flight_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('website_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_selected_flights', to='ai_itinerary.trip')),
            ],
        ),
    ]
