import { chromium } from 'playwright';
const URL = process.argv[2];
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 375, height: 812 }, isMobile: true, deviceScaleFactor: 3 });
const page = await ctx.newPage();
const cdp = await ctx.newCDPSession(page);
await cdp.send('Network.enable');
const reqs = new Map(); const done = [];
cdp.on('Network.responseReceived', e => reqs.set(e.requestId, { type: e.type, url: e.response.url, mime: e.response.mimeType }));
cdp.on('Network.loadingFinished', e => { const r = reqs.get(e.requestId); if (r) done.push({ ...r, kb: e.encodedDataLength/1024 }); });
await page.goto(URL, { waitUntil: 'load', timeout: 60000 });
await page.waitForTimeout(8000);
const imgs = done.filter(d => d.type === 'Image').sort((a,b) => b.kb - a.kb);
console.log('image requests:');
for (const i of imgs) console.log(Math.round(i.kb)+'KB', i.mime, i.url.slice(0, 140));
const dups = {};
for (const i of imgs) dups[i.url] = (dups[i.url]||0)+1;
console.log('duplicates:', JSON.stringify(Object.entries(dups).filter(([,c]) => c > 1).map(([u,c]) => c + 'x ' + u.slice(0,100))));
await b.close();
