-- Migration 071: Impressions — provider_performance_metrics,
--                market_intelligence, pricing_intelligence, demand_signals tables.
--
-- Intelligence layer tables that power the "Impressions" analytics sold to
-- providers (how often their profile appeared in search), the admin Market
-- Intelligence dashboard, and the Pricing Intelligence widget.
--   • provider_performance_metrics — per-period impression/view/booking roll-ups
--     per provider, surfaced in the Provider Analytics dashboard.
--   • market_intelligence — aggregated destination/country-level insights
--     generated by the TravelPulse AI for admin/tourism-board reports.
--   • pricing_intelligence — market price benchmarks by service type and
--     destination, used by the pricing recommendation widget.
--   • demand_signals — lightweight, destination-scoped demand counters
--     (search_count, no_results_count) for the Market Intelligence layer.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS; safe to re-run.

-- ─── provider_performance_metrics ───────────────────────────────────────────

CREATE TABLE IF NOT EXISTS provider_performance_metrics (
  id                    VARCHAR PRIMARY KEY,
  provider_id           VARCHAR NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  period                VARCHAR(20) NOT NULL,                   -- daily | weekly | monthly
  period_start          TIMESTAMP NOT NULL,
  impressions           INT DEFAULT 0,
  profile_views         INT DEFAULT 0,
  search_appearances    INT DEFAULT 0,
  inquiries             INT DEFAULT 0,
  bookings              INT DEFAULT 0,
  revenue               NUMERIC(10, 2) DEFAULT 0,
  avg_response_time     INT,                                    -- minutes
  conversion_rate       NUMERIC(5, 2),
  competitor_rank       INT,
  price_competitiveness VARCHAR(20),                            -- below_avg | avg | above_avg
  created_at            TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ppm_provider_period
  ON provider_performance_metrics(provider_id, period, period_start DESC);

-- ─── market_intelligence ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS market_intelligence (
  id             VARCHAR PRIMARY KEY,
  report_type    VARCHAR(50) NOT NULL,                          -- destination | country | service_type | seasonal
  target_entity  VARCHAR(255) NOT NULL,
  period         VARCHAR(20) NOT NULL,
  period_start   TIMESTAMP NOT NULL,
  metrics        JSONB NOT NULL,
  insights       JSONB,
  recommendations JSONB,
  data_quality   VARCHAR(20) DEFAULT 'high',                    -- high | medium | low
  created_at     TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mi_report_entity
  ON market_intelligence(report_type, target_entity, period_start DESC);

-- ─── pricing_intelligence ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pricing_intelligence (
  id           VARCHAR PRIMARY KEY,
  service_type VARCHAR(50) NOT NULL,
  destination  VARCHAR(255),
  country      VARCHAR(100),
  avg_price    NUMERIC(10, 2),
  min_price    NUMERIC(10, 2),
  max_price    NUMERIC(10, 2),
  median_price NUMERIC(10, 2),
  price_range  VARCHAR(50),                                     -- budget | mid-range | luxury
  sample_size  INT,
  period       VARCHAR(20),
  period_start TIMESTAMP,
  created_at   TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pi_service_destination
  ON pricing_intelligence(service_type, destination);

-- ─── demand_signals ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS demand_signals (
  id                VARCHAR PRIMARY KEY,
  destination       VARCHAR(255) NOT NULL,
  country           VARCHAR(100),
  service_type      VARCHAR(50),
  search_count      INT DEFAULT 0,
  no_results_count  INT DEFAULT 0,
  avg_budget        NUMERIC(10, 2),
  peak_month        VARCHAR(20),
  travelers_profile JSONB,
  origin_countries  JSONB,
  last_updated      TIMESTAMP DEFAULT NOW(),
  created_at        TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ds_destination_service
  ON demand_signals(destination, service_type);
