-- 183_itinerary_comparisons_segmentation_proposal.sql
--
-- WHAT: additive nullable `itinerary_comparisons.segmentation_proposal` JSONB. Carries the
-- trip-segmentation engine's output (server/services/trip-segmentation.service.ts,
-- `proposeSegmentation`) for the paid optimize run that produced this comparison row. NO DEFAULT,
-- NO BACKFILL — every existing comparison row predates the engine's wiring and stays NULL
-- (honest-or-absent, CLAUDE.md §13); a NULL value means "no recommendation was computed for this
-- run" (including a run whose segmentation computation failed — CLAUDE.md §15b posture: the
-- engine failing must never fail the paid optimize, so the caller logs and omits rather than
-- retrying or blocking). Deliberately NO CHECK constraint — this is a RECOMMENDATION-ONLY payload
-- (docs/briefs/TRIP_SEGMENTATION_DESIGN.md §5b, Phase 1): nothing reads this column to make a
-- money or ownership decision, no vocabulary needs app-side enforcement beyond what the engine's
-- own TypeScript types already give the writer, and the migration-159/166/173/181 house posture
-- is to keep a CHECK off a jsonb blob column to avoid the publish-time preflight trap entirely.
--
-- WHY: WP-C shipped `proposeSegmentation` dark (no caller). This column is where the caller
-- (server/itinerary-optimizer.ts, generateOptimizedItineraries's completion point) persists the
-- proposal it computes from the SAME baseline items already resolved for that optimize run — see
-- server/services/optimizer-segmentation-bridge.service.ts for the input-building + failure-safe
-- wrapper. Recommendation-only: no trip_segments table, no materialization, no accept/apply action
-- in this wave (that is the `trip_segments` / Option B work, ruled separately in
-- docs/briefs/TRIP_SEGMENTATION_DESIGN.md §6a).
--
-- Declared on the `itineraryComparisons` pgTable in shared/schema.ts in the SAME commit (the
-- deploy-push durability rule — an undeclared column the code depends on is silently reverted by
-- the next Replit publish-time drizzle-kit push).
--
-- Idempotent-ALTER pattern per the migration-159/161/173/181 house style.

ALTER TABLE itinerary_comparisons ADD COLUMN IF NOT EXISTS segmentation_proposal JSONB;
