-- 242_drop_provider_availability.sql
--
-- Partner Demand 2C (ledger 2026-08-17-partner-demand-2c-sunset). DROP the confirmed-orphan
-- `provider_availability` table (R1 verify-then-delete; R7 Q4 measured 0 rows, no owners).
--
-- SAFETY (verified before this DROP, not assumed from row count):
--   * NO insert path anywhere in the repo (grep: no .insert(providerAvailability), no raw
--     `INSERT INTO provider_availability`) — so the table is structurally 0-row on the live path.
--   * NO readers — declared availability lives in provider_availability_schedule +
--     provider_blackout_dates; bookable truth in vendor_availability_slots.
--   * Its ONE live writer — a raw `UPDATE provider_availability … ` on the booking-confirmation
--     path (booking.service.ts confirmBookingPayment) — matched 0 rows on every call (a proven
--     no-op) and was REMOVED in the same change that adds this migration, so nothing references
--     the relation when this runs.
--   * The `providerAvailability` pgTable declaration is deleted from shared/schema.ts in the same
--     change, so the Replit deploy push does not recreate the table after this drops it
--     (publish-trap rule). Not to be confused with the LIVE `provider_availability_schedule`.
--
-- IF EXISTS so a fresh/push-canonical environment that never had the table does not error.

DROP TABLE IF EXISTS provider_availability;
