-- 248_drop_travel_pulse_cities_unique_index.sql
--
-- Replit Publish compares the development and production schemas, but does not
-- run this application's data-cleanup migrations against production. Production
-- retains historical duplicate normalized city/country pairs, so attempting to
-- add the expression UNIQUE index from migration 230 makes Publish fail.
--
-- Keep the development and production schemas compatible without mutating
-- production data. City enrollment and TravelPulse seeding already use normalized
-- application-level lookups; DB-level uniqueness remains intentionally deferred
-- until production duplicates are cleaned through an approved data operation.
--
-- Idempotent: safe for fresh databases where migration 230 created the index and
-- existing development databases where it is already absent.
DROP INDEX IF EXISTS travel_pulse_cities_city_country_unique;