-- 337 — city_events: whether the start TIME is known (ledger `2026-10-01-city-events-nine-seed`).
-- HELD FOR DECISION-MAKER REVIEW before push (decision-maker, Oct 1, 2026: "Migration 337, same rule
-- as 335/336: nullable boolean, no DEFAULT/CHECK/index, applied twice locally, held in the PR for my
-- review. Null and false both mean 'date only' — the card omits startTime unless it's true.").
--
-- ONE ADDITIVE, NULLABLE COLUMN. NO DEFAULT, NO CHECK, NO INDEX, NO BACKFILL — the publish-trap
-- posture; declared in shared/schema.ts (deploy-push durability). A publish prompt offering exactly
-- this `ADD COLUMN IF NOT EXISTS` is inside §20's born-column carve-out, and declining it is also safe:
-- boot adds the same column.
--
-- start_time_known — TRUE when the organiser published the time of day `starts_at` carries. NULL and
--              FALSE both mean "the date is known, the time is not": `starts_at` then holds local
--              midnight only because the column is a timestamp, and the card OMITS its start time
--              rather than saying "00:00" (§13). Existing rows stay NULL — no backfill, because no
--              one stated their times as known.
ALTER TABLE city_events ADD COLUMN IF NOT EXISTS start_time_known boolean;
