-- Migration 207: service_provider_forms.office_location — the provider's account-level
-- office / place-of-business location (DECISIONS.md ruling 85).
--
-- WHAT + WHY. The provider business-profile table (service_provider_forms) carries a NOT-NULL
-- free-text `address` + `country` but NO structured coordinate for the account — the address is
-- never geocoded, and the storefront deliberately does not read it. Ruling 85 adds ONE account-
-- level confirmed location so a provider can place their place-of-business ONCE (typed address OR a
-- dropped map pin, geocoded through the existing POST /api/geocode, persisted ONLY on explicit
-- Confirm via the reused LocationPointPicker) and have it PRE-FILL the meeting pin of every NEW
-- listing they create — instead of re-placing the same pin on each one. The pin stays fully
-- overridable/removable per listing; the office coords are provider-CONFIRMED, so seeding a new
-- listing with them is honest (§13). This is provider-owned CONFIG, not a money/identity/rate
-- field — nothing derives a charge from it.
--
-- SHAPE. jsonb { address: string, lat: number, lng: number } — mirroring the cart_items.pickup_location
-- precedent (migration 205). Written owner-gated (session user's OWN row) via PATCH
-- /api/provider-application through a hand-written zod ALLOWLIST that validates finite lat∈[-90,90]/
-- lng∈[-180,180] (or explicit null-to-clear); a client coordinate is never trusted beyond that
-- validation + the client Confirm gate.
--
-- §13. NULL = "office location not set" — the honest default on every pre-207 row. It is NEVER
-- backfilled with a guessed or city-centre coordinate (the location='Unknown' lesson): an unset
-- office simply produces no new-listing pre-fill.
--
-- PUBLISH-TRAP. Additive-nullable column ONLY. NO DB CHECK / NO NOT NULL / NO DEFAULT / NO backfill
-- (the migration-205/206 additive posture) → nothing for the preflight CONSTRAINT_MANIFEST, no
-- publish-time deploy-push failure. Also DECLARED in shared/schema.ts (serviceProviderForms.
-- officeLocation) so the Replit deploy-push cannot drop it. Idempotent.

ALTER TABLE service_provider_forms
  ADD COLUMN IF NOT EXISTS office_location jsonb;
