# Generated by Django 5.2.1 on 2025-07-21 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='users/covers/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/images/')),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('is_local_expert', models.BooleanField(default=False)),
                ('is_service_provider', models.BooleanField(default=False)),
                ('is_post_holiday_package', models.BooleanField(default=False)),
                ('is_sell_packages', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('travel_style', models.JSONField(default=list)),
                ('preferred_months', models.JSONField(default=list)),
                ('meal_preference', models.CharField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalExpertForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.JSONField(default=list)),
                ('years_in_city', models.IntegerField()),
                ('offer_service', models.BooleanField(default=False)),
                ('gov_id', models.FileField(upload_to='localExpert/')),
                ('travel_licence', models.FileField(upload_to='localExpert/')),
                ('instagram_link', models.TextField(blank=True, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('linkedin_link', models.TextField(blank=True, null=True)),
                ('services', models.JSONField(default=list)),
                ('service_availability', models.IntegerField(default=15)),
                ('price_expectation', models.IntegerField()),
                ('confirm_age', models.BooleanField(default=False)),
                ('t_and_c', models.BooleanField(default=False)),
                ('partnership', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=100)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.TextField()),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField()),
                ('whatsapp', models.CharField()),
                ('country', models.CharField()),
                ('address', models.TextField()),
                ('booking_link', models.TextField(blank=True, null=True)),
                ('gst', models.CharField()),
                ('instagram_link', models.TextField(blank=True, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('linkedin_link', models.TextField(blank=True, null=True)),
                ('photo1', models.FileField(blank=True, null=True, upload_to='serviceProvider/')),
                ('photo2', models.FileField(blank=True, null=True, upload_to='serviceProvider/')),
                ('photo3', models.FileField(blank=True, null=True, upload_to='serviceProvider/')),
                ('photo4', models.FileField(blank=True, null=True, upload_to='serviceProvider/')),
                ('photo5', models.FileField(blank=True, null=True, upload_to='serviceProvider/')),
                ('business_type', models.CharField()),
                ('service_offers', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('instant_booking', models.BooleanField(default=False)),
                ('business_logo', models.FileField(upload_to='serviceProvider/')),
                ('business_license', models.FileField(upload_to='serviceProvider/')),
                ('business_gst_tax', models.FileField(upload_to='serviceProvider/')),
                ('t_and_c', models.BooleanField(default=False)),
                ('info_confirmation', models.BooleanField(default=False)),
                ('contact_request', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
