# Generated by Django 5.2.3 on 2025-08-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_localexpertform_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localexpertform',
            name='short_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localexpertform',
            name='price_expectation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
